from cogant.schemas.core import Node as Node, NodeKind as NodeKind
from dataclasses import dataclass
from typing import Any

@dataclass
class LanguageFact:
    fact_type: str
    language: str
    data: dict[str, Any]

@dataclass
class NormalizedFact:
    node_kind: NodeKind
    name: str
    qualified_name: str
    path: str | None = ...
    language: str | None = ...
    metadata: dict[str, Any] | None = ...
    def __post_init__(self) -> None: ...

class CanonicalNormalizer:
    def __init__(self) -> None: ...
    def normalize(self, fact: LanguageFact) -> NormalizedFact | None: ...
    def normalize_batch(self, facts: list[LanguageFact]) -> list[NormalizedFact | None]: ...
    def to_node(self, normalized: NormalizedFact, node_id: str) -> Node: ...
    def get_normalization_log(self) -> list[dict[str, Any]]: ...
    def get_normalization_stats(self) -> dict[str, int]: ...
