from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

@dataclass
class ParsedSymbol:
    name: str
    kind: str
    line_start: int
    line_end: int
    qualified_name: str
    docstring: str = ...
    metadata: dict[str, Any] = field(default_factory=dict)

@dataclass
class ParsedFile:
    path: str
    language: str
    symbols: list[ParsedSymbol] = field(default_factory=list)
    imports: list[dict[str, Any]] = field(default_factory=list)
    calls: list[dict[str, Any]] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

class TreeSitterParser:
    def __init__(self) -> None: ...
    def available_languages(self) -> set[str]: ...
    def supported_extensions(self) -> set[str]: ...
    def language_for_path(self, path: Path) -> str | None: ...
    def parse_file(self, path: Path) -> ParsedFile | None: ...
    def parse_source(self, source: str, language: str, path: str = '') -> ParsedFile | None: ...

class _BaseExtractor:
    def extract_symbols(self, tree: Any, source: bytes, path: str) -> list[ParsedSymbol]: ...
    def extract_imports(self, tree: Any, source: bytes) -> list[dict[str, Any]]: ...
    def extract_calls(self, tree: Any, source: bytes) -> list[dict[str, Any]]: ...

class _PythonExtractor(_BaseExtractor):
    def extract_symbols(self, tree: Any, source: bytes, path: str) -> list[ParsedSymbol]: ...
    def extract_imports(self, tree: Any, source: bytes) -> list[dict[str, Any]]: ...
    def extract_calls(self, tree: Any, source: bytes) -> list[dict[str, Any]]: ...

class _JavaScriptExtractor(_BaseExtractor):
    def extract_symbols(self, tree: Any, source: bytes, path: str) -> list[ParsedSymbol]: ...
    def extract_imports(self, tree: Any, source: bytes) -> list[dict[str, Any]]: ...
    def extract_calls(self, tree: Any, source: bytes) -> list[dict[str, Any]]: ...

def get_tree_sitter_parser() -> TreeSitterParser: ...
