from pathlib import Path

__all__ = ["organize_run_dir", "migrate_output_tree"]

def organize_run_dir(run_dir: str | Path) -> dict[str, list[str]]: ...
def migrate_output_tree(
    output_root: str | Path, *, dry_run: bool = ...
) -> dict[str, list[str]]: ...
