from _typeshed import Incomplete
from pathlib import Path

logger: Incomplete

def organize_run_dir(flat_dir: Path, *, dry_run: bool = False) -> Path | None: ...
def migrate_output_tree(output_root: Path, *, suite: str = 'control_positive', examples: list[str] | None = None, dry_run: bool = False) -> int: ...
def main(argv: list[str] | None = None) -> int: ...
