__all__ = [
    "OBSERVATION_KEYWORDS",
    "ACTION_KEYWORDS",
    "POLICY_KEYWORDS",
    "PREFERENCE_KEYWORDS",
    "CONTEXT_KEYWORDS",
    "CONFIG_KEYWORDS",
    "FEATURE_FLAG_KEYWORDS",
    "CIRCUIT_BREAKER_KEYWORDS",
    "RETRY_KEYWORDS",
    "SINGLETON_KEYWORDS",
    "PARAMETER_KEYWORDS",
    "STATE_MACHINE_KEYWORDS",
    "RATE_LIMITER_KEYWORDS",
]

OBSERVATION_KEYWORDS: list[str]
ACTION_KEYWORDS: list[str]
POLICY_KEYWORDS: list[str]
PREFERENCE_KEYWORDS: list[str]
CONTEXT_KEYWORDS: list[str]
CONFIG_KEYWORDS: list[str]
FEATURE_FLAG_KEYWORDS: list[str]
CIRCUIT_BREAKER_KEYWORDS: list[str]
RETRY_KEYWORDS: list[str]
SINGLETON_KEYWORDS: list[str]
PARAMETER_KEYWORDS: list[str]
STATE_MACHINE_KEYWORDS: list[str]
RATE_LIMITER_KEYWORDS: list[str]
