from cogant.graph.queries import GraphQuery as GraphQuery
from cogant.schemas.core import EdgeKind as EdgeKind, NodeKind as NodeKind
from cogant.schemas.graph import ProgramGraph as ProgramGraph
from cogant.schemas.semantic import ConfidenceTier as ConfidenceTier, MappingKind as MappingKind, ProvenanceRecord as ProvenanceRecord, SemanticMapping as SemanticMapping
from cogant.translate.engine import TranslationRule as TranslationRule
from typing import Any

class RetryPatternRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...

class ErrorBoundaryRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...

class SingletonAccessRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...

class CircuitBreakerRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...
