from typing import Any

from cogant.graph.queries import GraphQuery as GraphQuery
from cogant.schemas.core import Node as Node
from cogant.schemas.graph import ProgramGraph as ProgramGraph
from cogant.schemas.semantic import MappingKind as MappingKind
from cogant.schemas.semantic import SemanticMapping as SemanticMapping
from cogant.translate.engine import RuleExplanation as RuleExplanation
from cogant.translate.engine import TranslationRule as TranslationRule

OBSERVATION_KEYWORDS: Any
ACTION_KEYWORDS: Any

class ObservationRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    def explain(self, node: Node, graph: ProgramGraph, query: GraphQuery) -> RuleExplanation: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...
    def to_gnn_role(self) -> str: ...

class ActionRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    def explain(self, node: Node, graph: ProgramGraph, query: GraphQuery) -> RuleExplanation: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...
    def to_gnn_role(self) -> str: ...

class PolicyRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...
    def to_gnn_role(self) -> str: ...

class PreferenceRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...
    def to_gnn_role(self) -> str: ...

class ContextRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...
    def to_gnn_role(self) -> str: ...
