from cogant.graph.queries import GraphQuery as GraphQuery
from cogant.schemas.core import EdgeKind as EdgeKind, Node as Node, NodeKind as NodeKind
from cogant.schemas.graph import ProgramGraph as ProgramGraph
from cogant.schemas.semantic import ConfidenceTier as ConfidenceTier, MappingKind as MappingKind, ProvenanceRecord as ProvenanceRecord, SemanticMapping as SemanticMapping
from cogant.translate.engine import RuleExplanation as RuleExplanation, TranslationRule as TranslationRule
from typing import Any

class ReadOnlyInputRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...

class MutatingSubsystemRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    def explain(self, node: Node, graph: ProgramGraph, query: GraphQuery) -> RuleExplanation: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...

class InheritanceRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...

class ContainmentRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...

class DataPipelineRule(TranslationRule):
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    def name(self) -> str: ...
    @property
    def mapping_kind(self) -> MappingKind: ...
