from dataclasses import dataclass, field
from rich.console import Console

@dataclass
class DoctorCheck:
    name: str
    status: str
    detail: str = ...
    @property
    def icon(self) -> str: ...

@dataclass
class DoctorReport:
    checks: list[DoctorCheck] = field(default_factory=list)
    def add(self, check: DoctorCheck) -> None: ...
    @property
    def ok(self) -> bool: ...
    @property
    def has_warnings(self) -> bool: ...
    @property
    def verdict(self) -> str: ...

MIN_PYTHON: tuple[int, int]

def run_doctor() -> DoctorReport: ...
def render_report(console: Console, report: DoctorReport) -> None: ...
def doctor_command(console: Console | None = None) -> int: ...
