"""Project scaffolding helpers for ``cogant init``.

This module provides a second-generation scaffold that writes a
``cogant.toml`` configuration file alongside a ``.gitignore`` entry
for ``cogant_output/``. It is deliberately decoupled from the Typer
``init`` command in :mod:`cogant.cli.main` so it can be reused as a
library function (from tests, notebooks, or other CLI front-ends)
without spawning a subprocess.

Design goals:

* **Idempotent.** Running :func:`scaffold_project` twice must not
  clobber an existing ``cogant.toml`` or ``.gitignore``. Instead, the
  function appends the ``cogant_output/`` line to ``.gitignore`` only
  when it is not already present.
* **No pipeline imports.** Scaffolding has to work on a machine where
  ``cogant translate`` would fail; we keep the dependency surface to
  the standard library plus :mod:`rich` for console output.
* **Friendly path errors.** :func:`validate_repo_path` returns a
  structured :class:`RepoPathError` when the user mistypes a path.
  The error carries a best-guess ``hint`` from
  :func:`difflib.get_close_matches` so callers can render consistent
  ``Did you mean …?`` messages regardless of entry point.
"""

from __future__ import annotations

import difflib
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

from rich.console import Console

__all__ = [
    "DEFAULT_COGANT_TOML",
    "GITIGNORE_ENTRY",
    "RepoPathError",
    "ScaffoldResult",
    "render_repo_path_error",
    "render_scaffold_summary",
    "scaffold_project",
    "suggest_repo_path",
    "validate_repo_path",
]


# --------------------------------------------------------------- constants --


DEFAULT_COGANT_TOML: str = """# COGANT project configuration
# Generated by `cogant init`. Safe to edit — re-running init never
# clobbers this file.

[project]
name = "untitled"
version = "0.1.0"

[pipeline]
# Directories the ingest stage will skip. Paths are repo-relative.
skip_dirs = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "node_modules",
    "dist",
    "build",
    "cogant_output",
]

# Where bundle.json and derived artifacts will be written.
output_dir = "cogant_output"

# Skip the dynamic-analysis stage by default. Flip this to `false`
# once you have a coverage database to feed in via `--coverage`.
no_dynamic = true

# Stages to run, in order. Comment out to use the pipeline default.
# stages = [
#     "ingest", "static", "normalize", "graph", "translate",
#     "statespace", "process", "export", "validate",
# ]

[translate]
# Plugin-specific overrides go under [translate.<plugin_name>].
"""

GITIGNORE_ENTRY: str = "cogant_output/"

_COGANT_TOML_NAME: str = "cogant.toml"
_GITIGNORE_NAME: str = ".gitignore"


# --------------------------------------------------------------- data types --


@dataclass
class ScaffoldResult:
    """Structured result of a :func:`scaffold_project` call.

    The dataclass lets callers (CLI or tests) reason about what
    actually happened on disk without re-stat'ing files. Every path
    attribute is absolute so tests can pass it straight into
    ``Path.read_text``.
    """

    project_dir: Path
    toml_path: Path
    gitignore_path: Path
    toml_created: bool
    gitignore_created: bool
    gitignore_updated: bool
    notes: list[str] = field(default_factory=list)


@dataclass
class RepoPathError:
    """Description of a bad repository path plus a best-guess hint.

    Emitted by :func:`validate_repo_path` so every caller can render
    the same ``ERROR / Hint`` panel. The ``hint`` is ``None`` when no
    close sibling could be found.
    """

    path: Path
    reason: str  # human-readable
    hint: Path | None


# --------------------------------------------------------------- validation --


def _iter_sibling_names(parent: Path) -> Iterable[str]:
    """Yield the names of entries under ``parent`` without raising.

    We only consume these for fuzzy matching, so swallowing
    :class:`OSError` is fine; an empty iterator just yields no
    suggestions.
    """

    try:
        for entry in parent.iterdir():
            yield entry.name
    except OSError:
        return


def suggest_repo_path(path: Path) -> Path | None:
    """Return the closest-matching sibling path, if any.

    Uses :func:`difflib.get_close_matches` against entries in the
    target's parent directory. Returns ``None`` when the parent
    itself does not exist or no reasonable match is found.
    """

    parent = path.parent
    if not parent.exists():
        return None
    candidates = list(_iter_sibling_names(parent))
    if not candidates:
        return None
    matches = difflib.get_close_matches(path.name, candidates, n=1, cutoff=0.6)
    if not matches:
        return None
    return parent / matches[0]


def validate_repo_path(path: str | Path) -> RepoPathError | None:
    """Validate that ``path`` refers to an existing directory.

    Returns ``None`` when the path is healthy, otherwise a
    :class:`RepoPathError` describing the problem. This function is
    side-effect free: it never creates, reads, or writes files.
    """

    resolved = Path(path)
    if not resolved.exists():
        return RepoPathError(
            path=resolved,
            reason=f"Repo not found: {resolved}",
            hint=suggest_repo_path(resolved),
        )
    if resolved.is_file():
        return RepoPathError(
            path=resolved,
            reason=f"Expected a directory but got a file: {resolved}",
            hint=None,
        )
    return None


def render_repo_path_error(console: Console, error: RepoPathError) -> None:
    """Print a :class:`RepoPathError` using the canonical format.

    Format::

        [red]ERROR[/red] Repo not found: {path}
        [yellow]Hint:[/yellow] Did you mean {similar}?
    """

    console.print(f"[red]ERROR[/red] {error.reason}")
    if error.hint is not None:
        console.print(f"[yellow]Hint:[/yellow] Did you mean {error.hint}?")


# --------------------------------------------------------------- scaffolding --


def _ensure_gitignore(
    gitignore_path: Path, entry: str = GITIGNORE_ENTRY
) -> tuple[bool, bool]:
    """Guarantee ``entry`` appears in ``gitignore_path``.

    Returns a ``(created, updated)`` tuple:

    * ``created=True`` when the file did not exist and was written fresh.
    * ``updated=True`` when the file existed and we appended ``entry``.

    Both flags are ``False`` when the entry was already present —
    :func:`scaffold_project` treats that as a no-op.
    """

    if not gitignore_path.exists():
        gitignore_path.write_text(f"{entry}\n")
        return True, False

    existing = gitignore_path.read_text()
    existing_lines = {line.strip() for line in existing.splitlines()}
    if entry in existing_lines:
        return False, False

    suffix = "" if existing.endswith("\n") else "\n"
    gitignore_path.write_text(f"{existing}{suffix}{entry}\n")
    return False, True


def scaffold_project(project_dir: str | Path) -> ScaffoldResult:
    """Create or update the scaffold files for a COGANT project.

    Writes ``cogant.toml`` (never clobbered) and ensures
    ``.gitignore`` contains ``cogant_output/``. Creates
    ``project_dir`` itself if missing, which is convenient for
    ``cogant init ./new_project`` on a fresh checkout.

    Parameters
    ----------
    project_dir:
        Path to the project root. Created if missing. Must resolve
        to a directory (not a file) when it already exists — the
        caller is expected to have run :func:`validate_repo_path`
        first when the user provided the path from the CLI.
    """

    project_dir = Path(project_dir)
    if project_dir.exists() and project_dir.is_file():
        raise NotADirectoryError(
            f"scaffold_project expected a directory, got a file: {project_dir}"
        )
    project_dir.mkdir(parents=True, exist_ok=True)

    toml_path = project_dir / _COGANT_TOML_NAME
    gitignore_path = project_dir / _GITIGNORE_NAME
    notes: list[str] = []

    toml_created = False
    if not toml_path.exists():
        toml_path.write_text(DEFAULT_COGANT_TOML)
        toml_created = True
    else:
        notes.append(f"{_COGANT_TOML_NAME} already exists — left untouched")

    gitignore_created, gitignore_updated = _ensure_gitignore(gitignore_path)
    if not (gitignore_created or gitignore_updated):
        notes.append(
            f"{_GITIGNORE_NAME} already lists {GITIGNORE_ENTRY!r}"
        )

    return ScaffoldResult(
        project_dir=project_dir,
        toml_path=toml_path,
        gitignore_path=gitignore_path,
        toml_created=toml_created,
        gitignore_created=gitignore_created,
        gitignore_updated=gitignore_updated,
        notes=notes,
    )


def render_scaffold_summary(console: Console, result: ScaffoldResult) -> None:
    """Print a human-readable summary of a :class:`ScaffoldResult`.

    Used by CLI callers that want the same output format across
    entry points. Tests exercise :func:`scaffold_project` directly,
    so this helper is kept intentionally thin.
    """

    console.print(
        f"[green]Scaffold complete[/green] at [cyan]{result.project_dir}[/cyan]"
    )

    if result.toml_created:
        console.print(f"  [green]+[/green] created {result.toml_path.name}")
    else:
        console.print(f"  [dim]=[/dim] kept existing {result.toml_path.name}")

    if result.gitignore_created:
        console.print(f"  [green]+[/green] created {result.gitignore_path.name}")
    elif result.gitignore_updated:
        console.print(
            f"  [green]~[/green] appended {GITIGNORE_ENTRY!r} to "
            f"{result.gitignore_path.name}"
        )
    else:
        console.print(
            f"  [dim]=[/dim] {result.gitignore_path.name} already had "
            f"{GITIGNORE_ENTRY!r}"
        )

    for note in result.notes:
        console.print(f"  [dim]note:[/dim] {note}")
