from pathlib import Path
from typing import Any

console: Any
app: Any

_apply_upstream_pipeline_flags: Any
_friendly_pipeline_error: Any
_parse_step_csv: Any
_render_upstream_pipeline_table: Any
_run_pipeline_with_progress: Any

def init(
    path: str = ..., quiet: bool = ..., check_env: bool = ..., run: bool = ..., yes: bool = ...
) -> None: ...
def doctor() -> None: ...
def scan(target: str = ..., format: str = ...) -> None: ...
def extract_static(
    target: str = ..., output: str | None = ..., layout_output: bool = ...
) -> None: ...
def extract_dynamic(target: str = ..., traces: str | None = ...) -> None: ...
def graph(target: str = ..., output: str | None = ...) -> None: ...
def translate(
    target: str = ...,
    config_file: str | None = ...,
    skip_stages: str | None = ...,
    output_dir: str = ...,
    layout_output: bool = ...,
    no_dynamic: bool = ...,
    coverage_path: str | None = ...,
    trace_path: str | None = ...,
    incremental: str | None = ...,
    cache_dir: str | None = ...,
) -> None: ...
def analyze(
    target: str = ...,
    incremental: str | None = ...,
    output_dir: str = ...,
    cache_dir: str | None = ...,
    no_dynamic: bool = ...,
    skip_stages: str | None = ...,
    quiet: bool = ...,
) -> None: ...
def statespace(target: str = ..., output: str | None = ...) -> None: ...
def process(target: str = ..., no_dynamic: bool = ...) -> None: ...
def export_gnn(bundle_path: str = ..., output_dir: str = ..., format: str = ...) -> None: ...
def render(bundle_path: str = ..., output_dir: str = ...) -> None: ...
def viz(run_dir: str = ...) -> None: ...
def validate(bundle_path: str = ...) -> None: ...
def diff(path_a: str = ..., path_b: str = ..., output: str | None = ...) -> None: ...
def changed(
    path: Path = ...,
    since: str = ...,
    python_only: bool = ...,
    source_only: bool = ...,
    output: Path | None = ...,
) -> None: ...
def explain(repo_path: str = ..., node_name: str = ..., output_format: str = ...) -> None: ...
def benchmark(target: str = ..., iterations: int = ..., no_dynamic: bool = ...) -> None: ...
