from pathlib import Path

from _typeshed import Incomplete

from cogant.api.bundle import Bundle as Bundle
from cogant.api.pipeline import PipelineConfig as PipelineConfig
from cogant.api.pipeline import PipelineRunner as PipelineRunner
from cogant.api.session import Session as Session
from cogant.cli.doctor import doctor_command as doctor_command
from cogant.cli.doctor import render_report as render_report
from cogant.cli.doctor import run_doctor as run_doctor
from cogant.cli.migrate import migrate_app as migrate_app
from cogant.cli.plugin import plugin_app as plugin_app
from cogant.reverse.cli import reverse_command as reverse_command
from cogant.reverse.cli import roundtrip_command as roundtrip_command

logger: Incomplete
console: Incomplete
app: Incomplete

def init(path: str = ..., quiet: bool = ..., check_env: bool = ..., run: bool = ..., yes: bool = ...) -> None: ...
def doctor() -> None: ...
def scan(target: str = ..., format: str = ...) -> None: ...
def extract_static(target: str = ..., output: str | None = ..., layout_output: bool = ...) -> None: ...
def extract_dynamic(target: str = ..., traces: str | None = ...) -> None: ...
def graph(target: str = ..., output: str | None = ...) -> None: ...
def translate(target: str = ..., config_file: str | None = ..., skip_stages: str | None = ..., output_dir: str = ..., layout_output: bool = ..., no_dynamic: bool = ..., coverage_path: str | None = ..., trace_path: str | None = ..., incremental: str | None = ..., cache_dir: str | None = ...) -> None: ...
def statespace(target: str = ..., output: str | None = ...) -> None: ...
def process(target: str = ..., no_dynamic: bool = ...) -> None: ...
def export_gnn(bundle_path: str = ..., output_dir: str = ..., format: str = ...) -> None: ...
def render(bundle_path: str = ..., output_dir: str = ...) -> None: ...
def viz(run_dir: str = ...) -> None: ...
def validate(bundle_path: str = ...) -> None: ...
def diff(path_a: str = ..., path_b: str = ..., output: str | None = ...) -> None: ...
def changed(path: Path = ..., since: str = ..., python_only: bool = ..., source_only: bool = ..., output: Path | None = ...) -> None: ...
def explain(repo_path: str = ..., node_name: str = ..., output_format: str = ...) -> None: ...
def benchmark(target: str = ..., iterations: int = ..., no_dynamic: bool = ...) -> None: ...
