from typing import Any

from cogant.schemas.semantic import ConfidenceTier as ConfidenceTier
from cogant.schemas.semantic import SemanticMapping as SemanticMapping

class ConfidenceModel:
    STATIC_ONLY_THRESHOLD: float
    STATIC_PLUS_RUNTIME_THRESHOLD: float
    RUNTIME_ONLY_THRESHOLD: float
    HUMAN_REVIEWED_THRESHOLD: float
    def __init__(self) -> None: ...
    def compute(self, mapping: SemanticMapping) -> float: ...
    def compute_confidence_score(self, mapping: SemanticMapping) -> float: ...
    def determine_confidence_tier(self, mapping: SemanticMapping, score: float | None = None) -> ConfidenceTier: ...
    def score_evidence_diversity(self, mapping: SemanticMapping) -> float: ...
    def detect_conflicts(self, mapping: SemanticMapping) -> list[float]: ...
    def update_mapping_confidence(self, mapping: SemanticMapping) -> None: ...
    def score_batch(self, mappings: list[SemanticMapping]) -> None: ...
    def get_high_confidence_mappings(self, mappings: list[SemanticMapping], threshold: float = 0.7) -> list[SemanticMapping]: ...
    def get_low_confidence_mappings(self, mappings: list[SemanticMapping], threshold: float = 0.6) -> list[SemanticMapping]: ...
    def get_conflicted_mappings(self, mappings: list[SemanticMapping]) -> list[SemanticMapping]: ...
    def get_scoring_report(self) -> dict[str, Any]: ...
    def clear_log(self) -> None: ...
