import abc
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from _typeshed import Incomplete as Incomplete

from cogant.graph.queries import GraphQuery as GraphQuery
from cogant.schemas.core import Node as Node
from cogant.schemas.graph import ProgramGraph as ProgramGraph
from cogant.schemas.semantic import ConfidenceTier as ConfidenceTier
from cogant.schemas.semantic import MappingKind as MappingKind
from cogant.schemas.semantic import SemanticMapping as SemanticMapping

logger: Incomplete

@dataclass
class RuleExplanation:
    rule_name: str
    priority: int
    fired: bool
    reason: str
    evidence: list[str] = field(default_factory=list)
    mapping_kind: str | None = ...
    def to_dict(self) -> dict[str, Any]: ...

class TranslationRule(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def matches(self, graph: ProgramGraph, query: GraphQuery) -> list[dict[str, Any]]: ...
    @abstractmethod
    def apply(self, graph: ProgramGraph, match: dict[str, Any]) -> SemanticMapping | None: ...
    @property
    @abstractmethod
    def name(self) -> str: ...
    @property
    @abstractmethod
    def mapping_kind(self) -> MappingKind: ...
    @property
    def priority(self) -> int: ...
    def explain(self, node: Node, graph: ProgramGraph, query: GraphQuery) -> RuleExplanation: ...

class TranslationEngine:
    rules: list[TranslationRule]
    mappings: dict[str, SemanticMapping]
    max_iterations: Incomplete
    def __init__(self, max_iterations: int = 10) -> None: ...
    def register_rule(self, rule: TranslationRule) -> None: ...
    def translate(self, graph: ProgramGraph, rule_filter: list[str] | None = None) -> list[SemanticMapping]: ...
    def translate_with_confidence(self, graph: ProgramGraph, rule_filter: list[str] | None = None) -> list[SemanticMapping]: ...
    def get_coverage_report(self, graph: ProgramGraph) -> dict[str, Any]: ...
    def get_mappings_by_kind(self, kind: MappingKind) -> list[SemanticMapping]: ...
    def get_mappings_by_confidence(self, tier: ConfidenceTier) -> list[SemanticMapping]: ...
    def get_mapping(self, mapping_id: str) -> SemanticMapping | None: ...
    def get_match_log(self) -> list[dict[str, Any]]: ...
    def get_statistics(self) -> dict[str, Any]: ...
