from typing import Any

from cogant.schemas.semantic import ConfidenceTier as ConfidenceTier
from cogant.schemas.semantic import SemanticMapping as SemanticMapping

class ReviewManager:
    mappings: dict[str, SemanticMapping]
    review_history: list[dict[str, Any]]
    def __init__(self) -> None: ...
    def add_mapping(self, mapping: SemanticMapping) -> None: ...
    def accept_mapping(self, mapping_id: str, reviewer: str, feedback: str | None = None) -> bool: ...
    def reject_mapping(self, mapping_id: str, reviewer: str, reason: str) -> bool: ...
    def edit_mapping(self, mapping_id: str, reviewer: str, updates: dict[str, Any]) -> bool: ...
    def split_mapping(self, mapping_id: str, reviewer: str, split_definitions: list[dict[str, Any]]) -> list[str]: ...
    def merge_mappings(self, mapping_ids: list[str], reviewer: str, merged_definition: dict[str, Any]) -> str | None: ...
    def get_mapping_for_review(self, mapping_id: str) -> SemanticMapping | None: ...
    def get_mappings_by_status(self, status: str) -> list[SemanticMapping]: ...
    def get_unreviewed_mappings(self) -> list[SemanticMapping]: ...
    def get_review_summary(self) -> dict[str, Any]: ...
    def get_review_history(self) -> list[dict[str, Any]]: ...
    def export_reviewed_mappings(self) -> list[SemanticMapping]: ...
