import abc
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any

@dataclass
class PluginMetadata:
    name: str
    version: str
    author: str = ...
    description: str = ...

class Plugin(ABC, metaclass=abc.ABCMeta):
    metadata: Any
    def __init__(self, metadata: PluginMetadata) -> None: ...
    @abstractmethod
    def initialize(self, config: dict[str, Any]) -> None: ...
    @abstractmethod
    def shutdown(self) -> None: ...

class LanguagePlugin(Plugin, metaclass=abc.ABCMeta):
    supported_languages: set[str]
    @abstractmethod
    def parse(self, source_code: str) -> dict[str, Any]: ...
    @abstractmethod
    def extract_symbols(self, ast: dict[str, Any]) -> list[dict[str, Any]]: ...
    @abstractmethod
    def extract_types(self, ast: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def resolve_imports(self, ast: dict[str, Any]) -> list[str]: ...

class TracePlugin(Plugin, metaclass=abc.ABCMeta):
    @abstractmethod
    def parse_trace(self, trace_file: str) -> dict[str, Any]: ...
    @abstractmethod
    def parse_coverage(self, coverage_file: str) -> dict[str, Any]: ...
    @abstractmethod
    def extract_call_graph(self, trace_data: dict[str, Any]) -> dict[str, Any]: ...

class NormalizerPlugin(Plugin, metaclass=abc.ABCMeta):
    @abstractmethod
    def normalize(self, data: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def validate_schema(self, data: dict[str, Any]) -> bool: ...

class TranslationRulePlugin(Plugin, metaclass=abc.ABCMeta):
    @abstractmethod
    def translate_nodes(self, graph_nodes: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
    @abstractmethod
    def translate_edges(self, graph_edges: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
    @abstractmethod
    def compute_features(self, node: dict[str, Any]) -> list[float]: ...

class StateSpacePlugin(Plugin, metaclass=abc.ABCMeta):
    @abstractmethod
    def extract_states(self, gnn_model: dict[str, Any]) -> list[dict[str, Any]]: ...
    @abstractmethod
    def extract_observations(self, gnn_model: dict[str, Any]) -> list[dict[str, Any]]: ...
    @abstractmethod
    def extract_actions(self, gnn_model: dict[str, Any]) -> list[dict[str, Any]]: ...
    @abstractmethod
    def learn_policies(
        self,
        states: list[dict[str, Any]],
        observations: list[dict[str, Any]],
        actions: list[dict[str, Any]],
    ) -> list[dict[str, Any]]: ...

class ProcessModelPlugin(Plugin, metaclass=abc.ABCMeta):
    @abstractmethod
    def extract_stages(self, bundle: dict[str, Any]) -> list[dict[str, Any]]: ...
    @abstractmethod
    def extract_dependencies(self, stages: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
    @abstractmethod
    def compute_ordering(
        self, stages: list[dict[str, Any]], dependencies: list[dict[str, Any]]
    ) -> list[str]: ...

class ExportPlugin(Plugin, metaclass=abc.ABCMeta):
    supported_formats: set[str]
    @abstractmethod
    def export(self, bundle: dict[str, Any], output_path: str, format: str) -> None: ...
    @abstractmethod
    def get_format_info(self, format: str) -> dict[str, Any]: ...

class ValidationPlugin(Plugin, metaclass=abc.ABCMeta):
    @abstractmethod
    def validate(self, bundle: dict[str, Any]) -> dict[str, Any]: ...
    @abstractmethod
    def compute_quality_metrics(self, bundle: dict[str, Any]) -> dict[str, float]: ...

class VisualizationPlugin(Plugin, metaclass=abc.ABCMeta):
    supported_visualizations: set[str]
    @abstractmethod
    def render(self, bundle: dict[str, Any], output_path: str, viz_type: str) -> None: ...
    @abstractmethod
    def get_viz_info(self, viz_type: str) -> dict[str, Any]: ...
