from cogant.plugins.base import LanguagePlugin
from pathlib import Path
from typing import Any

__all__ = ['JsLanguagePlugin']

class JsLanguagePlugin(LanguagePlugin):
    supported_languages: set[str]
    def __init__(self) -> None: ...
    def initialize(self, config: dict[str, Any]) -> None: ...
    def shutdown(self) -> None: ...
    def parse(self, source_code: str) -> dict[str, Any]: ...
    def extract_symbols(self, ast: dict[str, Any]) -> list[dict[str, Any]]: ...
    def extract_types(self, ast: dict[str, Any]) -> dict[str, Any]: ...
    def resolve_imports(self, ast: dict[str, Any]) -> list[str]: ...
    def parse_path(self, path: Path) -> Any: ...
