from _typeshed import Incomplete
from dataclasses import dataclass
from typing import Any

logger: Incomplete
ENTRY_POINT_GROUP: str

@dataclass
class PluginInfo:
    name: str
    version: str = ...
    entry_point: str = ...
    loaded: bool = ...
    error: str | None = ...

class PluginRegistry:
    def __init__(self) -> None: ...
    def discover(self) -> list[PluginInfo]: ...
    def load(self, name: str) -> PluginInfo: ...
    def list_plugins(self) -> list[str]: ...
    def get_plugin_info(self, name: str) -> PluginInfo: ...
    def get_loaded_object(self, name: str) -> Any: ...
