from _typeshed import Incomplete

from cogant.process.extractor import ProcessModel as ProcessModel
from cogant.schemas.graph import ProgramGraph as ProgramGraph
from cogant.statespace.compiler import StateSpaceModel as StateSpaceModel
from cogant.validate.schema_check import ValidationIssue as ValidationIssue

logger: Incomplete

class IntegrityChecker:
    issues: list[ValidationIssue]
    def __init__(self) -> None: ...
    def check_program_graph(self, graph: ProgramGraph) -> list[ValidationIssue]: ...
    def check_state_space(self, state_space: StateSpaceModel) -> list[ValidationIssue]: ...
    def check_process_model(self, process: ProcessModel) -> list[ValidationIssue]: ...
    def get_issues(self) -> list[ValidationIssue]: ...
    def is_valid(self) -> bool: ...
