from dataclasses import dataclass

from cogant.process.extractor import ProcessModel as ProcessModel
from cogant.schemas.graph import ProgramGraph as ProgramGraph
from cogant.statespace.compiler import StateSpaceModel as StateSpaceModel

@dataclass
class ValidationIssue:
    id: str
    severity: str
    category: str
    message: str
    affected_ids: list[str]
    recommendation: str | None = ...

class SchemaValidator:
    issues: list[ValidationIssue]
    def __init__(self) -> None: ...
    def validate_program_graph(self, graph: ProgramGraph) -> list[ValidationIssue]: ...
    def validate_state_space(self, state_space: StateSpaceModel) -> list[ValidationIssue]: ...
    def validate_process_model(self, process: ProcessModel) -> list[ValidationIssue]: ...
    def get_issues(self) -> list[ValidationIssue]: ...
    def get_errors(self) -> list[ValidationIssue]: ...
    def get_warnings(self) -> list[ValidationIssue]: ...
    def is_valid(self) -> bool: ...
