from cogant.translate.dsl.schema import DSLCondition as DSLCondition, DSLRule as DSLRule, DSLRuleSet as DSLRuleSet, KNOWN_CONDITION_KEYS as KNOWN_CONDITION_KEYS
from pathlib import Path
from typing import Any

def load_rules_from_yaml(path: Path | str) -> DSLRuleSet: ...
def load_rules_from_dict(data: dict[str, Any]) -> DSLRuleSet: ...
