__all__ = ["migrate_v1_0_to_v1_1", "migrate_gnn"]

def migrate_v1_0_to_v1_1(gnn_text: str) -> tuple[str, list[str]]: ...
def migrate_gnn(gnn_text: str, target: str = ...) -> tuple[str, list[str]]: ...
