from cogant.plugins import LanguagePlugin, PluginMetadata

class MyLanguagePlugin(LanguagePlugin):
    def __init__(self):
        super().__init__(PluginMetadata(name="MyLang", version="1.0.0"))
        self.supported_languages = {"mylang"}

    def initialize(self, config): ...
    def shutdown(self): ...
    def parse(self, source_code): ...
    def extract_symbols(self, ast): ...
    def extract_types(self, ast): ...
    def resolve_imports(self, ast): ...
