from cogant.plugins import ExportPlugin, PluginMetadata

class MyFormat(ExportPlugin):
    def __init__(self):
        super().__init__(PluginMetadata(name="MyFormat", version="1.0.0"))
        self.supported_formats = {"myformat"}

    def initialize(self, config): ...
    def shutdown(self): ...
    def export(self, bundle, output_path, fmt): ...
    def get_format_info(self, fmt): ...
