from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

__all__: list[str]

@dataclass(frozen=True)
class TargetMetrics:
    target_id: str
    kind: str
    source: str
    score: float | None
    node_count: int = ...
    edge_count: int = ...
    mapping_count: int = ...
    gnn_package_files: int = ...
    wall_time_s: float = ...
    role_distribution: dict[str, int] = ...
    confidence_distribution: dict[str, int] = ...
    parser_status: str = ...
    roundtrip_status: str = ...
    generated_code_status: str = ...
    graph_edit_normalized: float | None = ...
    visual_artifact_count: int = ...
    failure_reasons: tuple[str, ...] = ...
    failed_steps: tuple[str, ...] = ...
    presence: dict[str, bool] = ...

    def as_jsonable(self) -> dict[str, Any]: ...

class BatchDashboardGenerator:
    output_root: Path

    def __init__(
        self,
        output_root: Path | str,
        *,
        manifest: dict[str, Any] | None = ...,
    ) -> None: ...
    def load_manifest(self) -> dict[str, Any]: ...
    def discover_targets(self, manifest: dict[str, Any] | None = ...) -> list[dict[str, Any]]: ...
    def collect_target_metrics(
        self, manifest: dict[str, Any] | None = ...
    ) -> list[TargetMetrics]: ...
    def render_summary_csv(self, metrics: list[TargetMetrics]) -> str: ...
    def render_metrics_json(
        self,
        metrics: list[TargetMetrics],
        manifest: dict[str, Any] | None = ...,
    ) -> str: ...
    def render_mermaid_node_bar(self, metrics: list[TargetMetrics]) -> str: ...
    def render_mermaid_edge_bar(self, metrics: list[TargetMetrics]) -> str: ...
    def render_mermaid_score_pie(self, metrics: list[TargetMetrics]) -> str: ...
    def render_mermaid_visual_completeness_pie(self, metrics: list[TargetMetrics]) -> str: ...
    def render_mermaid_parser_status_pie(self, metrics: list[TargetMetrics]) -> str: ...
    def render_mermaid_role_distribution(self, metrics: list[TargetMetrics]) -> str: ...
    def render_mermaid_confidence_distribution(self, metrics: list[TargetMetrics]) -> str: ...
    def render_mermaid_roundtrip_status_pie(self, metrics: list[TargetMetrics]) -> str: ...
    def render_mermaid_failure_reasons_pie(self, metrics: list[TargetMetrics]) -> str: ...
    def render_mermaid_gantt(
        self,
        manifest: dict[str, Any] | None = ...,
        *,
        max_rows: int = ...,
    ) -> str: ...
    def render_markdown_dashboard(
        self,
        metrics: list[TargetMetrics],
        manifest: dict[str, Any] | None = ...,
    ) -> str: ...
    def write_all(self, dashboard_dir: Path | str | None = ...) -> dict[str, Path]: ...

def write_batch_dashboard(
    output_root: Path | str,
    *,
    dashboard_dir: Path | str | None = ...,
    manifest: dict[str, Any] | None = ...,
) -> dict[str, Path]: ...
