from pathlib import Path
from typing import Any

__all__ = ['render_bundle_site', 'render_index_html', 'render_graph_html', 'render_statespace_html', 'render_css']

def render_bundle_site(output_dir: str | Path, *, target: str, repo_summary: dict[str, Any]) -> Path: ...
def render_index_html(*, target: str, repo_summary: dict[str, Any]) -> str: ...
def render_graph_html() -> str: ...
def render_statespace_html() -> str: ...
def render_css() -> str: ...
