"""Type stubs for ExportView."""

from __future__ import annotations

from typing import Any

class ExportView:
    """Summary and diagnostic visualizations for export operations."""

    def __init__(self) -> None: ...
    def plot_export_formats(self, export_results: dict[str, Any]) -> Any: ...
    def to_mermaid_export_pipeline(self) -> str: ...
    def plot_bundle_composition(self, bundle: dict[str, Any]) -> Any: ...
    def to_png(self, fig: Any, output_path: str, dpi: int = 150) -> str: ...
    def to_pdf(self, fig: Any, output_path: str) -> str: ...
