from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from cogant.schemas.graph import ProgramGraph as ProgramGraph

@dataclass
class D3Node:
    id: str
    label: str
    group: str
    size: int = ...
    color: str | None = ...
    language: str | None = ...
    kind: str | None = ...
    path: str | None = ...
    qualified_name: str | None = ...

@dataclass
class D3Link:
    source: str
    target: str
    label: str
    weight: float = ...

class GraphVisualizer:
    nodes: list[D3Node]
    links: list[D3Link]
    metadata: dict[str, Any]
    def __init__(self) -> None: ...
    def from_program_graph(self, graph: dict[str, Any]) -> GraphVisualizer: ...
    def from_typed_graph(self, graph: ProgramGraph) -> GraphVisualizer: ...
    def cluster_by_package(self) -> GraphVisualizer: ...
    def cluster_by_language(self) -> GraphVisualizer: ...
    def cluster_by_kind(self) -> GraphVisualizer: ...
    def cluster_by_service(self) -> GraphVisualizer: ...
    def get_clusters(self) -> dict[str, list[str]]: ...
    def filter_by_edge_type(self, edge_type: str) -> GraphVisualizer: ...
    def render_html(self, output_path: str) -> str: ...
    def render_svg(self, output_path: str) -> str: ...
    def to_d3_json(self) -> dict[str, Any]: ...
