"""HTMLSiteRenderer: Generate complete static HTML site with all views."""

from pathlib import Path
from typing import Dict, Any, Optional, List
import json
import logging

logger = logging.getLogger(__name__)


class HTMLSiteRenderer:
    """
    Generate a complete static HTML site for analysis results.

    Creates:
      - index.html (overview and navigation)
      - graph/ (program graph visualizations)
      - models/ (state space and process models)
      - provenance/ (lineage inspector)
      - assets/ (CSS, JavaScript, data files)
    """

    def __init__(self, bundle: Dict[str, Any]):
        """
        Initialize renderer.

        Args:
            bundle: Analysis bundle to render.
        """
        self.bundle = bundle
        self.output_dir: Optional[Path] = None

    def render(self, output_dir: str) -> Path:
        """
        Generate complete HTML site.

        Args:
            output_dir: Directory to write site to.

        Returns:
            Path to index.html
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"Rendering HTML site to {output_dir}")

        # Create subdirectories
        (self.output_dir / "graph").mkdir(exist_ok=True)
        (self.output_dir / "models").mkdir(exist_ok=True)
        (self.output_dir / "provenance").mkdir(exist_ok=True)
        (self.output_dir / "assets").mkdir(exist_ok=True)

        # Render pages
        self._render_index()
        self._render_graph()
        self._render_models()
        self._render_provenance()
        self._render_assets()
        self._render_data()

        index_path = self.output_dir / "index.html"
        logger.info(f"HTML site rendered to {index_path}")
        return index_path

    def _render_index(self) -> None:
        """Render main index page."""
        summary = self.bundle.get("artifacts", {})
        errors = len(self.bundle.get("errors", []))
        target_name = self.bundle.get("target", "Unknown")
        stage_results = self.bundle.get("stage_results", {})
        stages_completed = len(stage_results)
        stage_list_html = "".join(
            self._render_stage_item(stage)
            for stage in [
                "ingest", "static", "normalize", "graph", "translate",
                "statespace", "process", "export", "validate",
            ]
        )
        errors_style = "" if errors > 0 else "display: none;"
        error_list_html = "".join(
            f"<li>{error}</li>" for error in self.bundle.get("errors", [])[:10]
        )

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>COGANT Analysis Report</title>
    <link rel="stylesheet" href="assets/style.css">
</head>
<body>
    <header class="header">
        <div class="container">
            <h1>COGANT Analysis Report</h1>
            <p>Codebase-to-GNN Translation Engine</p>
        </div>
    </header>

    <nav class="navbar">
        <div class="container">
            <ul>
                <li><a href="index.html" class="active">Overview</a></li>
                <li><a href="graph/program_graph.html">Program Graph</a></li>
                <li><a href="models/state_space.html">State Space</a></li>
                <li><a href="models/process.html">Process</a></li>
                <li><a href="provenance/index.html">Provenance</a></li>
            </ul>
        </div>
    </nav>

    <main class="container">
        <section class="hero">
            <h2>Analysis Summary</h2>
            <div class="stats">
                <div class="stat">
                    <div class="stat-value">{target_name}</div>
                    <div class="stat-label">Target</div>
                </div>
                <div class="stat">
                    <div class="stat-value">{stages_completed} / 9</div>
                    <div class="stat-label">Stages Completed</div>
                </div>
                <div class="stat">
                    <div class="stat-value">{errors}</div>
                    <div class="stat-label">Errors</div>
                </div>
            </div>
        </section>

        <section class="pipeline">
            <h2>Pipeline Status</h2>
            <div class="stage-list">
                {stage_list_html}
            </div>
        </section>

        <section class="errors" style="{errors_style}">
            <h2>Errors</h2>
            <ul>
                {error_list_html}
            </ul>
        </section>

        <footer class="footer">
            <p>Generated by <strong>COGANT v0.1.0</strong></p>
            <p>Codebase-to-GNN Translation Engine</p>
        </footer>
    </main>
</body>
</html>
"""
        with open(self.output_dir / "index.html", "w") as f:
            f.write(html)

    def _render_stage_item(self, stage: str) -> str:
        """Render single pipeline stage."""
        stage_results = self.bundle.get("stage_results", {})
        completed = stage in stage_results
        status = "completed" if completed else "pending"
        icon = "✓" if completed else "○"

        return f"""
        <div class="stage-item {status}">
            <span class="stage-icon">{icon}</span>
            <span class="stage-name">{stage}</span>
        </div>
        """

    def _render_graph(self) -> None:
        """Render program graph page."""
        html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Program Graph</title>
    <link rel="stylesheet" href="../assets/style.css">
    <script src="https://d3js.org/d3.v7.min.js"></script>
</head>
<body>
    <header class="header">
        <div class="container">
            <h1>Program Graph</h1>
        </div>
    </header>

    <nav class="navbar">
        <div class="container">
            <ul>
                <li><a href="../index.html">Overview</a></li>
                <li><a href="program_graph.html" class="active">Program Graph</a></li>
                <li><a href="../models/state_space.html">State Space</a></li>
            </ul>
        </div>
    </nav>

    <main class="container">
        <section>
            <div id="graph-container" style="width: 100%; height: 600px; background: #f9f9f9; border: 1px solid #ddd; border-radius: 4px;"></div>
            <p style="color: #999; text-align: center; margin-top: 10px;">Interactive program dependency graph (drag to move, scroll to zoom)</p>
        </section>

        <section style="margin-top: 40px;">
            <h2>Graph Statistics</h2>
            <dl>
                <dt>Nodes</dt>
                <dd id="node-count">Loading...</dd>
                <dt>Edges</dt>
                <dd id="edge-count">Loading...</dd>
            </dl>
        </section>

        <footer class="footer">
            <p>Generated by COGANT</p>
        </footer>
    </main>

    <script src="../assets/graph-vis.js"></script>
</body>
</html>
"""
        with open(self.output_dir / "graph" / "program_graph.html", "w") as f:
            f.write(html)

    def _render_models(self) -> None:
        """Render state space and process model pages."""
        # State space
        html_ss = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>State Space Model</title>
    <link rel="stylesheet" href="../assets/style.css">
</head>
<body>
    <header class="header">
        <div class="container">
            <h1>State Space Model</h1>
        </div>
    </header>

    <main class="container">
        <section>
            <h2>States</h2>
            <ul id="states-list"></ul>
        </section>
        <section>
            <h2>Observations</h2>
            <ul id="observations-list"></ul>
        </section>
        <footer class="footer">
            <p>Generated by COGANT</p>
        </footer>
    </main>

    <script src="../assets/statespace-data.js"></script>
</body>
</html>
"""
        with open(self.output_dir / "models" / "state_space.html", "w") as f:
            f.write(html_ss)

        # Process model
        html_proc = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Process Model</title>
    <link rel="stylesheet" href="../assets/style.css">
</head>
<body>
    <header class="header">
        <div class="container">
            <h1>Process/Execution Model</h1>
        </div>
    </header>

    <main class="container">
        <section>
            <h2>Pipeline Stages</h2>
            <div id="gantt-chart"></div>
        </section>
        <footer class="footer">
            <p>Generated by COGANT</p>
        </footer>
    </main>

    <script src="../assets/process-data.js"></script>
</body>
</html>
"""
        with open(self.output_dir / "models" / "process.html", "w") as f:
            f.write(html_proc)

    def _render_provenance(self) -> None:
        """Render provenance inspector."""
        html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Provenance Inspector</title>
    <link rel="stylesheet" href="../assets/style.css">
</head>
<body>
    <header class="header">
        <div class="container">
            <h1>Provenance Inspector</h1>
        </div>
    </header>

    <main class="container">
        <section>
            <h2>Analysis Lineage</h2>
            <p>Shows the complete lineage of analysis artifacts, including:</p>
            <ul>
                <li>Input data and sources</li>
                <li>Processing stages and transformations</li>
                <li>Output artifacts and their dependencies</li>
                <li>Validation results</li>
            </ul>
        </section>

        <section>
            <h2>Metadata</h2>
            <pre id="metadata" style="background: #f5f5f5; padding: 15px; border-radius: 4px; overflow-x: auto;">
Loading metadata...
            </pre>
        </section>

        <footer class="footer">
            <p>Generated by COGANT</p>
        </footer>
    </main>

    <script src="../assets/provenance-data.js"></script>
</body>
</html>
"""
        with open(self.output_dir / "provenance" / "index.html", "w") as f:
            f.write(html)

    def _render_assets(self) -> None:
        """Render CSS and JavaScript files."""
        # Main CSS
        css = """
/* COGANT - Modern CSS */

:root {
    --primary: #667eea;
    --secondary: #764ba2;
    --success: #43e97b;
    --danger: #f5576c;
    --warning: #ffd89b;
    --info: #4facfe;
    --light: #f9f9f9;
    --dark: #333;
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: #f5f5f5;
    color: #333;
    line-height: 1.6;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
}

.header {
    background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
    color: white;
    padding: 40px 0;
    text-align: center;
}

.header h1 {
    font-size: 2.5rem;
    margin-bottom: 10px;
}

.header p {
    opacity: 0.9;
    font-size: 1.1rem;
}

.navbar {
    background: white;
    border-bottom: 1px solid #ddd;
    position: sticky;
    top: 0;
    z-index: 100;
}

.navbar ul {
    display: flex;
    list-style: none;
}

.navbar li {
    margin: 0;
}

.navbar a {
    display: block;
    padding: 15px 20px;
    color: var(--primary);
    text-decoration: none;
    border-bottom: 3px solid transparent;
    transition: border-color 0.3s, color 0.3s;
}

.navbar a:hover,
.navbar a.active {
    border-bottom-color: var(--primary);
    color: var(--secondary);
}

main {
    background: white;
    margin: 30px auto;
    padding: 40px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

section {
    margin-bottom: 40px;
}

section h2 {
    color: var(--primary);
    border-bottom: 2px solid var(--primary);
    padding-bottom: 10px;
    margin-bottom: 20px;
}

.stats {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 20px;
    margin: 20px 0;
}

.stat {
    background: linear-gradient(135deg, var(--light) 0%, white 100%);
    border: 1px solid #ddd;
    padding: 20px;
    border-radius: 8px;
    text-align: center;
}

.stat-value {
    font-size: 2rem;
    font-weight: bold;
    color: var(--primary);
}

.stat-label {
    color: #666;
    margin-top: 10px;
}

.stage-list {
    display: flex;
    flex-direction: column;
    gap: 10px;
}

.stage-item {
    display: flex;
    align-items: center;
    padding: 15px;
    background: #f9f9f9;
    border-left: 4px solid #ddd;
    border-radius: 4px;
    transition: all 0.3s;
}

.stage-item.completed {
    border-left-color: var(--success);
    background: #f0fdf4;
}

.stage-item.pending {
    border-left-color: #ffd89b;
    background: #fffbf0;
}

.stage-icon {
    font-weight: bold;
    color: #666;
    min-width: 30px;
    text-align: center;
}

.stage-item.completed .stage-icon {
    color: var(--success);
}

.stage-name {
    flex: 1;
    font-weight: 500;
    color: #333;
}

.hero {
    background: linear-gradient(135deg, rgba(102, 126, 234, 0.1), rgba(118, 75, 162, 0.1));
    padding: 40px;
    border-radius: 8px;
    text-align: center;
    margin-bottom: 40px;
}

.errors {
    background: #fdf2f8;
    border-left: 4px solid var(--danger);
    padding: 20px;
    border-radius: 4px;
}

.errors ul {
    list-style: none;
    padding: 0;
}

.errors li {
    padding: 10px 0;
    border-bottom: 1px solid #eee;
    color: #c7254e;
}

.errors li:last-child {
    border-bottom: none;
}

.footer {
    text-align: center;
    color: #999;
    padding: 40px 0;
    border-top: 1px solid #ddd;
    margin-top: 40px;
}

@media (max-width: 768px) {
    .header h1 {
        font-size: 1.8rem;
    }

    main {
        padding: 20px;
    }

    .navbar ul {
        flex-wrap: wrap;
    }

    .navbar a {
        padding: 10px 15px;
        font-size: 0.9rem;
    }
}
"""
        with open(self.output_dir / "assets" / "style.css", "w") as f:
            f.write(css)

        # Graph visualization JS
        graph_js = """
// Graph visualization placeholder
console.log('Graph visualization loaded');

const data = window.graphData || { nodes: [], links: [] };
document.getElementById('node-count').textContent = data.nodes.length;
document.getElementById('edge-count').textContent = data.links.length;
"""
        with open(self.output_dir / "assets" / "graph-vis.js", "w") as f:
            f.write(graph_js)

        # State space data JS
        ss_js = """
// State space data placeholder
const stateSpaceData = window.stateSpaceData || {
    states: [],
    observations: [],
    actions: []
};
console.log('State space data loaded');
"""
        with open(self.output_dir / "assets" / "statespace-data.js", "w") as f:
            f.write(ss_js)

        # Process data JS
        proc_js = """
// Process model data placeholder
const processData = window.processData || {
    stages: [],
    dependencies: []
};
console.log('Process data loaded');
"""
        with open(self.output_dir / "assets" / "process-data.js", "w") as f:
            f.write(proc_js)

        # Provenance data JS
        prov_js = """
// Provenance data placeholder
const provenanceData = window.provenanceData || {};
document.getElementById('metadata').textContent = JSON.stringify(provenanceData, null, 2);
"""
        with open(self.output_dir / "assets" / "provenance-data.js", "w") as f:
            f.write(prov_js)

    def _render_data(self) -> None:
        """Render embedded data files."""
        # Create a data.json file with all bundle data
        data_file = self.output_dir / "assets" / "data.json"
        with open(data_file, "w") as f:
            json.dump(self.bundle, f, indent=2)

        logger.info(f"Bundle data written to {data_file}")
