from __future__ import annotations

from typing import Any

class MatrixVisualizer:
    def __init__(self) -> None: ...
    def plot_A_matrix(self, A: Any, labels: list[str] | None = None) -> Any: ...
    def plot_B_matrix(self, B: Any, action_idx: int = 0) -> Any: ...
    def plot_C_vector(self, C: Any) -> Any: ...
    def plot_D_vector(self, D: Any) -> Any: ...
    def plot_all_matrices(self, matrices: dict[str, Any]) -> Any: ...
    def to_png(self, fig: Any, output_path: str, dpi: int = 150) -> str: ...
    def to_pdf(self, fig: Any, output_path: str) -> str: ...
