from __future__ import annotations

from typing import Any

from cogant.process.extractor import ProcessModel as ProcessModel
from cogant.schemas.graph import ProgramGraph as ProgramGraph
from cogant.statespace.compiler import StateSpaceModel as StateSpaceModel

class MermaidGenerator:
    def __init__(self) -> None: ...
    def generate_class_diagram(self, graph: ProgramGraph) -> str: ...
    def generate_dependency_graph(self, graph: ProgramGraph) -> str: ...
    def generate_state_diagram(self, state_space: StateSpaceModel) -> str: ...
    def generate_sequence_diagram(
        self, process_model: ProcessModel | None = None, graph: ProgramGraph | None = None
    ) -> str: ...
    def generate_active_inference_diagram(self, state_space: StateSpaceModel) -> str: ...
    def generate_flowchart(self, graph: ProgramGraph, semantic_mappings: dict[str, Any]) -> str: ...
    def generate_all(
        self,
        graph: ProgramGraph,
        state_space: StateSpaceModel | None = None,
        process_model: ProcessModel | None = None,
        mappings: dict[str, Any] | None = None,
    ) -> dict[str, str]: ...
    def render_active_inference_diagram(self, state_space: StateSpaceModel) -> str: ...
    def render_rule_firing_trace(self, explanations: list[Any]) -> str: ...
    def render_markov_blanket(self, blanket: Any) -> str: ...
