"""Type stubs for NetworkView."""

from __future__ import annotations

from typing import Any

class NetworkView:
    """Visualizations for ProgramGraph network analysis."""

    def __init__(self) -> None: ...
    def plot_degree_distribution(self, metrics: dict[str, Any]) -> Any: ...
    def plot_centrality_ranking(self, centrality: dict[str, float], top_n: int = 15) -> Any: ...
    def summarize_hotspots(
        self,
        hotspots: dict[str, float],
        *,
        top_n: int = 10,
        role_hints: dict[str, str] | None = None,
    ) -> list[dict[str, Any]]: ...
    def plot_community_graph(self, graph: Any, communities: list[frozenset[Any]]) -> Any: ...
    def plot_adjacency_heatmap(
        self, matrix: list[list[int]], labels: list[str] | None = None
    ) -> Any: ...
    def plot_hotspot_treemap(self, hotspots: dict[str, float]) -> Any: ...
    def to_mermaid_community(self, communities: list[frozenset[Any]]) -> str: ...
    def to_mermaid_hotspots(self, hotspots: dict[str, float]) -> str: ...
    def to_png(self, fig: Any, output_path: str, dpi: int = 150) -> str: ...
    def to_pdf(self, fig: Any, output_path: str) -> str: ...
