from __future__ import annotations

from typing import Any

class PDFExporter:
    def __init__(self) -> None: ...
    def export_program_graph(self, graph: Any, output_path: str) -> str: ...
    def export_gnn_bundle(self, bundle: Any, output_path: str) -> str: ...
    def export_matrices(self, matrices: dict[str, Any], output_path: str) -> str: ...
    def export_markov_blanket(self, blanket: Any, output_path: str) -> str: ...
    def export_pipeline_report(self, pipeline_result: Any, output_path: str) -> str: ...
    def export_roundtrip_report(self, roundtrip_result: Any, output_path: str) -> str: ...
