from __future__ import annotations

from typing import Any

class PipelineVisualizer:
    def __init__(self) -> None: ...
    def render_stage_diagram(self) -> str: ...
    def render_timing_chart(self, timing_dict: dict[str, float]) -> Any: ...
    def render_stage_outputs(self, pipeline_result: Any) -> Any: ...
    def to_mermaid_pipeline(self) -> str: ...
    def to_png(self, output_path: str) -> str: ...
    def to_pdf(self, output_path: str) -> str: ...
