from typing import Any

from _typeshed import Incomplete as Incomplete

from cogant.schemas.graph import ProgramGraph as ProgramGraph
from cogant.statespace.compiler import StateSpaceModel as StateSpaceModel

logger: Incomplete

class StaticPlotter:
    def __init__(self) -> None: ...
    def plot_node_type_distribution(self, graph: ProgramGraph) -> str: ...
    def plot_edge_type_distribution(self, graph: ProgramGraph) -> str: ...
    def plot_confidence_distribution(self, mappings: dict[str, Any]) -> str: ...
    def plot_state_space_matrix(self, state_space: StateSpaceModel) -> str: ...
    def plot_state_space_matrix_html(self, state_space: StateSpaceModel, output_path: str) -> None: ...
    def plot_factor_graph(self, state_space: StateSpaceModel, output_path: str) -> None: ...
    def plot_ontology_sunburst(self, graph: ProgramGraph, mappings: dict[str, Any], output_path: str) -> None: ...
    def plot_confidence_radar(self, mappings: dict[str, Any], output_path: str) -> None: ...
