from _typeshed import Incomplete
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger: Incomplete

@dataclass
class RenderConfig:
    dpi: int = ...
    figsize: tuple[float, float] = ...
    title_fontsize: int = ...
    subtitle_fontsize: int = ...
    node_fontsize: int = ...
    edge_fontsize: int = ...
    banner_fontsize: int = ...
    footer_fontsize: int = ...
    node_size: int = ...
    edge_label_bg: str = ...
    cogant_version: str = ...
    max_label_len: int = ...
    show_legend: bool = ...
    show_footer: bool = ...
    max_render_nodes: int = ...
    max_render_edges: int = ...
    max_sequence_participants: int = ...
    extra_metadata: dict[str, str] = field(default_factory=dict)

def program_graph_dict_to_networkx(graph: dict[str, Any]) -> Any: ...
def render_program_graph_png(program_graph_json: Path, output_png: Path, *, cfg: RenderConfig | None = None, figsize: tuple[float, float] | None = None, dpi: int | None = None, source_label: str | None = None) -> bool: ...
def render_mermaid_file_to_png(mermaid_file: Path, output_png: Path, *, timeout: int = 120, allow_native_fallback: bool = True, cfg: RenderConfig | None = None) -> bool: ...
def render_all_mermaid_in_run(run_dir: Path, figures_dir: Path | None = None, *, cfg: RenderConfig | None = None) -> list[Path]: ...
def render_mermaid_text_to_png(text: str, output_png: Path, *, title: str | None = None, cfg: RenderConfig | None = None, figsize: tuple[float, float] | None = None, dpi: int | None = None, source_label: str | None = None) -> bool: ...
def render_svg_file_to_png(svg_file: Path, output_png: Path, *, timeout: int = 60) -> bool: ...
def render_all_svg_in_run(run_dir: Path) -> list[Path]: ...
def render_graphviz_dot_to_png(dot_file: Path, output_png: Path, *, timeout: int = 120) -> bool: ...
def render_all_dot_in_run(run_dir: Path) -> list[Path]: ...
def find_graph_dot(run_dir: Path) -> Path | None: ...
def render_state_space_factor_png(state_space: Any, output_png: Path, *, cfg: RenderConfig | None = None, figsize: tuple[float, float] | None = None, dpi: int | None = None, source_label: str | None = None) -> bool: ...
def render_connections_matrix_png(state_space: Any, output_png: Path, *, cfg: RenderConfig | None = None, source_label: str | None = None) -> bool: ...
def render_process_gantt_png(process_model: Any, output_png: Path, *, cfg: RenderConfig | None = None, figsize: tuple[float, float] | None = None, dpi: int | None = None, source_label: str | None = None) -> bool: ...
def render_markov_blanket_png(blanket_json: Path, output_png: Path, *, cfg: RenderConfig | None = None, source_label: str | None = None) -> bool: ...
def render_summary_cover_png(run_dir: Path, output_png: Path, *, cfg: RenderConfig | None = None) -> bool: ...
def render_gnn_markdown_png(md_file: Path, output_png: Path, *, cfg: RenderConfig | None = None, max_sections_per_page: int = 4, source_label: str | None = None) -> list[Path]: ...
def render_all_pngs(run_dir: Path, *, state_space: Any = None, process_model: Any = None, cfg: RenderConfig | None = None) -> dict[str, list[Path]]: ...
