"""Type stubs for StaticAnalysisView."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from matplotlib.figure import Figure

    from cogant.static.complexity import ComplexityReport
    from cogant.static.coupling import CouplingReport
    from cogant.static.dead_code import DeadCodeReport
    from cogant.static.metrics import HalsteadMetrics

class StaticAnalysisView:
    """Visualizations for static analysis reports."""

    def __init__(self) -> None: ...
    def plot_complexity_heatmap(
        self,
        report: ComplexityReport,
        threshold: int = 10,
    ) -> Figure | None: ...
    def plot_complexity_histogram(self, report: ComplexityReport) -> Figure | None: ...
    def plot_coupling_graph(self, report: CouplingReport) -> Figure | None: ...
    def plot_martin_metrics(self, report: CouplingReport) -> Figure | None: ...
    def plot_dead_code_summary(self, report: DeadCodeReport) -> Figure | None: ...
    def plot_halstead_radar(self, metrics: HalsteadMetrics) -> Figure | None: ...
    def to_mermaid_complexity(self, report: ComplexityReport) -> str: ...
    def to_mermaid_coupling(self, report: CouplingReport) -> str: ...
    def to_png(self, fig: Any, output_path: str, dpi: int = 150) -> str: ...
    def to_pdf(self, fig: Any, output_path: str) -> str: ...
