from dataclasses import dataclass, field

from _typeshed import Incomplete as Incomplete

from cogant.schemas.graph import ProgramGraph as ProgramGraph

logger: Incomplete

@dataclass
class RetryPolicy:
    id: str
    stage_id: str
    max_attempts: int = ...
    backoff_strategy: str = ...
    backoff_base: float = ...
    backoff_multiplier: float = ...

@dataclass
class BranchingPolicy:
    id: str
    stage_id: str
    decision_point: str
    branches: dict[str, str] = field(default_factory=dict)
    default_branch: str | None = ...

@dataclass
class CircuitBreakerPolicy:
    id: str
    stage_id: str
    failure_threshold: int = ...
    success_threshold: int = ...
    timeout: float = ...

class PolicyExtractor:
    graph: Incomplete
    retry_policies: dict[str, RetryPolicy]
    branching_policies: dict[str, BranchingPolicy]
    circuit_breaker_policies: dict[str, CircuitBreakerPolicy]
    def __init__(self, program_graph: ProgramGraph) -> None: ...
    def extract(self) -> dict[str, object]: ...
    def get_retry_policy(self, policy_id: str) -> RetryPolicy | None: ...
    def get_branching_policy(self, policy_id: str) -> BranchingPolicy | None: ...
    def get_circuit_breaker_policy(self, policy_id: str) -> CircuitBreakerPolicy | None: ...
    def list_policies_for_stage(self, stage_id: str) -> dict[str, list[object]]: ...
    def policy_count(self) -> int: ...
