from typing import Any

DEFAULT_COGANT_CONFIG: Any
DEFAULT_PYTHON_CONFIG: Any
DEFAULT_JAVASCRIPT_CONFIG: Any
DEFAULT_JAVA_CONFIG: Any
DEFAULT_LANGUAGE_CONFIGS: Any
DEFAULT_STAGES: Any
DEFAULT_PIPELINE_CONFIG: Any
MINIMAL_PIPELINE_CONFIG: Any
COMPREHENSIVE_PIPELINE_CONFIG: Any
DEFAULT_EXPORT_CONFIG: Any
MINIMAL_EXPORT_CONFIG: Any
GNN_EXPORT_CONFIG: Any
DEFAULT_VALIDATION_CONFIG: Any
STRICT_VALIDATION_CONFIG: Any
LENIENT_VALIDATION_CONFIG: Any
PRESETS: Any

def get_preset(name: str) -> dict[str, Any]: ...
