from .defaults import DEFAULT_COGANT_CONFIG as DEFAULT_COGANT_CONFIG, DEFAULT_EXPORT_CONFIG as DEFAULT_EXPORT_CONFIG, DEFAULT_PIPELINE_CONFIG as DEFAULT_PIPELINE_CONFIG, DEFAULT_VALIDATION_CONFIG as DEFAULT_VALIDATION_CONFIG, PRESETS as PRESETS
from .schema import CogantConfig as CogantConfig, ExportConfig as ExportConfig, PipelineConfig as PipelineConfig, ValidationConfig as ValidationConfig
from pathlib import Path
from typing import Any

HAS_YAML: bool

class ConfigLoadError(Exception): ...

class ConfigLoader:
    @staticmethod
    def load_from_yaml(path: str | Path) -> dict[str, Any]: ...
    @staticmethod
    def load_from_dict(data: dict[str, Any]) -> dict[str, Any]: ...
    @staticmethod
    def load_json_from_file(path: str | Path) -> dict[str, Any]: ...
    @staticmethod
    def merge_configs(base: dict[str, Any], override: dict[str, Any], deep: bool = True) -> dict[str, Any]: ...
    @staticmethod
    def load_default() -> dict[str, Any]: ...
    @staticmethod
    def load_preset(name: str) -> dict[str, Any]: ...
    @staticmethod
    def build_cogant_config(config_dict: dict[str, Any] | None = None, preset: str | None = None) -> CogantConfig: ...
    @staticmethod
    def build_pipeline_config(config_dict: dict[str, Any] | None = None, preset: str | None = None) -> PipelineConfig: ...
    @staticmethod
    def build_export_config(config_dict: dict[str, Any] | None = None, preset: str | None = None) -> ExportConfig: ...
    @staticmethod
    def build_validation_config(config_dict: dict[str, Any] | None = None, preset: str | None = None) -> ValidationConfig: ...
    @staticmethod
    def load_all_configs(yaml_path: str | Path | None = None, preset: str | None = None) -> dict[str, Any]: ...
