from .schema import CogantConfig as CogantConfig, ExportConfig as ExportConfig, ExportFormat as ExportFormat, LanguageConfig as LanguageConfig, LogLevel as LogLevel, PipelineConfig as PipelineConfig, PipelineStage as PipelineStage, ValidationConfig as ValidationConfig, ValidationLevel as ValidationLevel
from _typeshed import Incomplete
from typing import Any

def create_minimal_preset() -> dict[str, Any]: ...
def create_standard_preset() -> dict[str, Any]: ...
def create_comprehensive_preset() -> dict[str, Any]: ...
def create_gnn_focused_preset() -> dict[str, Any]: ...
def create_security_preset() -> dict[str, Any]: ...

PRESETS: Incomplete

def get_preset(name: str) -> dict[str, Any]: ...
def list_presets() -> list[str]: ...
