from typing import Any

def create_minimal_preset() -> dict[str, Any]: ...
def create_standard_preset() -> dict[str, Any]: ...
def create_comprehensive_preset() -> dict[str, Any]: ...
def create_gnn_focused_preset() -> dict[str, Any]: ...
def create_security_preset() -> dict[str, Any]: ...

PRESETS: Any

def get_preset(name: str) -> dict[str, Any]: ...
def list_presets() -> list[str]: ...
