from pathlib import Path
from typing import Any

from cogant.gnn.upstream_bridge.pipeline import (
    DEFAULT_SKIP_STEPS as DEFAULT_SKIP_STEPS,
)
from cogant.gnn.upstream_bridge.pipeline import (
    UPSTREAM_STEP_SCRIPTS as UPSTREAM_STEP_SCRIPTS,
)
from cogant.gnn.upstream_bridge.pipeline import (
    UpstreamPipelineConfig as UpstreamPipelineConfig,
)
from cogant.gnn.upstream_bridge.pipeline import (
    UpstreamPipelineResult as UpstreamPipelineResult,
)
from cogant.gnn.upstream_bridge.pipeline import (
    UpstreamStepResult as UpstreamStepResult,
)
from cogant.gnn.upstream_bridge.pipeline import (
    resolve_steps as resolve_steps,
)
from cogant.gnn.upstream_bridge.pipeline import (
    run_upstream_pipeline as run_upstream_pipeline,
)

class UpstreamGNNValidation:
    available: bool
    ok: bool
    errors: list[str]
    version: str | None
    skipped_reason: str | None
    def to_dict(self) -> dict[str, Any]: ...

def json_safe(obj: Any) -> Any: ...
def is_upstream_gnn_available() -> bool: ...
def upstream_version() -> str | None: ...
def run_upstream_validate_gnn(markdown: str) -> UpstreamGNNValidation: ...
def upstream_validate_markdown(markdown: str) -> UpstreamGNNValidation: ...
def upstream_validate_file_content(content: str, *, is_content: bool = True) -> dict[str, Any]: ...
def upstream_parse_file(path: str | Path) -> Any: ...
def upstream_discover_files(root: str | Path) -> Any: ...
def upstream_process_directory(input_dir: str | Path, output_dir: str | Path, **kwargs: Any) -> Any: ...
def upstream_process_directory_lightweight(
    input_dir: str | Path, output_dir: str | Path, **kwargs: Any
) -> Any: ...
def upstream_generate_report(*args: Any, **kwargs: Any) -> Any: ...
def upstream_validate_structure(*args: Any, **kwargs: Any) -> Any: ...
def upstream_module_info(*args: Any, **kwargs: Any) -> Any: ...
def upstream_process_multi_format(
    input_dir: str | Path, output_dir: str | Path, log: Any | None = None, **kwargs: Any
) -> Any: ...
def upstream_parse_formal(*args: Any, **kwargs: Any) -> Any: ...
def upstream_validate_syntax_formal(*args: Any, **kwargs: Any) -> Any: ...
def get_upstream_parsing_system() -> Any: ...
def get_upstream_gnn_format_enum() -> Any: ...
def parse_upstream_model_gnn_md(package_dir: str | Path) -> dict[str, Any]: ...
