from dataclasses import dataclass
from pathlib import Path
from typing import Any

UPSTREAM_STEP_SCRIPTS: tuple[str, ...]
DEFAULT_SKIP_STEPS: frozenset[int]

def resolve_steps(
    only: list[int] | None,
    skip: list[int] | None,
) -> list[int]: ...

@dataclass(frozen=True)
class UpstreamStepResult:
    step_index: int
    script: str
    status: str
    success: bool
    duration_s: float
    exit_code: int = ...
    memory_delta_mb: float = ...
    output_dir: str | None = ...
    error: str | None = ...
    def to_dict(self) -> dict[str, Any]: ...

@dataclass(frozen=True)
class UpstreamPipelineResult:
    available: bool
    steps: list[UpstreamStepResult]
    executed: list[int]
    skipped: list[int]
    total_duration_s: float
    output_dir: str | None
    target_dir: str | None
    error: str | None
    @property
    def success_count(self) -> int: ...
    @property
    def failure_count(self) -> int: ...
    @property
    def success_rate(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

@dataclass
class UpstreamPipelineConfig:
    target_dir: Path
    output_dir: Path
    only_steps: list[int] | None = ...
    skip_steps: list[int] = ...
    frameworks: str = ...
    llm_model: str | None = ...
    timesteps: int = ...
    verbose: bool = ...
    skip_llm: bool = ...

def run_upstream_pipeline(
    cfg: UpstreamPipelineConfig,
) -> UpstreamPipelineResult: ...
