from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from _typeshed import Incomplete

logger: Incomplete

@dataclass
class ProvenanceRecord:
    id: str
    target_id: str
    target_type: str
    evidence_type: str
    evidence_location: str
    confidence: float
    extraction_method: str
    timestamp: datetime
    metadata: dict[str, Any] = field(default_factory=dict)

class ProvenanceTracker:
    records: dict[str, ProvenanceRecord]
    target_to_records: dict[str, list[str]]
    def __init__(self) -> None: ...
    def add_record(self, target_id: str, target_type: str, evidence_type: str, evidence_location: str, extraction_method: str, confidence: float = 0.5, metadata: dict[str, Any] | None = None) -> str: ...
    def get_records_for_target(self, target_id: str) -> list[ProvenanceRecord]: ...
    def get_record(self, record_id: str) -> ProvenanceRecord | None: ...
    def compute_target_confidence(self, target_id: str) -> float: ...
    def get_records_by_type(self, target_type: str) -> list[ProvenanceRecord]: ...
    def get_records_by_evidence_type(self, evidence_type: str) -> list[ProvenanceRecord]: ...
    def get_records_by_method(self, method: str) -> list[ProvenanceRecord]: ...
    def get_coverage_statistics(self) -> dict[str, Any]: ...
    def query_records(self, target_id: str | None = None, target_type: str | None = None, evidence_type: str | None = None, min_confidence: float = 0.0) -> list[ProvenanceRecord]: ...
    def merge_tracker(self, other: ProvenanceTracker) -> None: ...
    def clear(self) -> None: ...
    def get_record_count(self) -> int: ...
    def get_target_count(self) -> int: ...
