from _typeshed import Incomplete
from dataclasses import dataclass, field
from typing import Any

@dataclass
class Counter:
    name: str
    value: int = ...
    labels: dict[str, str] = field(default_factory=dict)
    def inc(self, by: int = 1) -> None: ...
    def reset(self) -> None: ...

@dataclass
class Histogram:
    name: str
    buckets: list[float] = field(default_factory=Incomplete)
    def observe(self, value: float) -> None: ...
    def mean(self) -> float: ...
    def p95(self) -> float: ...
    def p99(self) -> float: ...
    def count(self) -> int: ...

class MetricsRegistry:
    def __init__(self) -> None: ...
    def counter(self, name: str, labels: dict[str, str] | None = None) -> Counter: ...
    def histogram(self, name: str) -> Histogram: ...
    def summary(self) -> dict[str, Any]: ...
    def reset_all(self) -> None: ...

registry: MetricsRegistry
