from dataclasses import dataclass

__all__ = ['AgentConfig']

@dataclass
class AgentConfig:
    max_steps: int = ...
    convergence_threshold: float = ...
    action_selection: str = ...
    seed: int = ...
