from pathlib import Path
from typing import Any

def default_demo_matrices() -> dict[str, Any]: ...
def run_deterministic_inference_demo(steps: int = ...) -> dict[str, Any]: ...
def write_inference_trace_artifact(run_dir: str | Path, *, steps: int = ...) -> Path: ...
