__all__ = ['free_energy', 'kl_divergence']

def kl_divergence(p: list[float], q: list[float]) -> float: ...
def free_energy(state_dist: list[float], obs_idx: int, A: list[list[float]], C: list[float], D: list[float]) -> float: ...
