
from typing import Any

from cogant.statespace.compiler import StateSpaceModel as StateSpaceModel

class CategoricalDistribution:
    categories: Any
    n: Any
    probabilities: Any
    dist: Any
    def __init__(self, categories: list[str], probabilities: list[float] | None = None) -> None: ...
    def sample(self) -> str: ...
    def log_prob(self, category: str) -> float: ...
    def entropy(self) -> float: ...
    def kl_divergence(self, other: CategoricalDistribution) -> float: ...
    def update(self, observation: str, likelihood: CategoricalDistribution) -> CategoricalDistribution: ...

class TransitionMatrix:
    states: Any
    actions: Any
    transitions: dict[str, dict[str, CategoricalDistribution]]
    def __init__(self, states: list[str], actions: list[str]) -> None: ...
    def set_transition(self, state: str, action: str, next_state: str, prob: float) -> None: ...
    def get_next_state_dist(self, state: str, action: str) -> CategoricalDistribution: ...
    @classmethod
    def from_state_space(cls, state_space: StateSpaceModel) -> TransitionMatrix: ...
