from _typeshed import Incomplete
from cogant.simulate.distributions import CategoricalDistribution as CategoricalDistribution
from cogant.simulate.free_energy import bayesian_belief_update as bayesian_belief_update, uniform_distribution as uniform_distribution
from cogant.statespace.compiler import StateSpaceModel as StateSpaceModel
from typing import Any

logger: Incomplete

class ModelRunner:
    model: Incomplete
    A: Incomplete
    B: Incomplete
    C: Incomplete
    D: Incomplete
    def __init__(self, seed: int | None = None, model: StateSpaceModel | None = None, A: list[list[float]] | None = None, B: list[list[list[float]]] | None = None, C: list[float] | None = None, D: list[float] | None = None) -> None: ...
    @property
    def has_generative_model(self) -> bool: ...
    def validate_model(self, state_space: StateSpaceModel) -> dict[str, Any]: ...
    def simulate_step(self, state_space: StateSpaceModel, current_state: dict[str, Any], action_id: str) -> dict[str, Any]: ...
    def run_simulation(self, state_space: StateSpaceModel, steps: int = 10) -> list[dict[str, Any]]: ...
    def vfe_from_beliefs(self, beliefs: list[float], observation: list[float] | None = None, prior: list[float] | None = None) -> float: ...
    def efe_for_policy(self, policy_action_sequence: list[int], beliefs: list[float] | None = None) -> float: ...
    def update_beliefs_from_observation(self, prior: list[float], observation_index: int) -> list[float]: ...
    def compute_free_energy(self, state: dict[str, Any], observation: str) -> float: ...
    def belief_update(self, prior_beliefs: dict[str, float], observation: str) -> dict[str, float]: ...
    def policy_evaluation(self, beliefs: dict[str, float], available_actions: list[str]) -> list[tuple[str, float]]: ...
    def active_inference_step(self, beliefs: dict[str, float], observation: str, state_space: StateSpaceModel) -> dict[str, Any]: ...
    def run_active_inference(self, state_space: StateSpaceModel, steps: int = 20) -> list[dict[str, Any]]: ...
    def generate_report(self, trace: list[dict[str, Any]]) -> str: ...
    def generate_trace(self, state_space: StateSpaceModel) -> dict[str, Any]: ...
