from typing import Any

class SimulationVisualizer:
    def __init__(self) -> None: ...
    def plot_free_energy_trajectory(self, trace: list[dict[str, Any]]) -> str: ...
    def plot_belief_evolution(self, trace: list[dict[str, Any]]) -> str: ...
    def plot_action_distribution(self, trace: list[dict[str, Any]]) -> str: ...
    def generate_mermaid_trajectory(self, trace: list[dict[str, Any]]) -> str: ...
    def generate_html_report(self, trace: list[dict[str, Any]], state_space: Any) -> str: ...
