
from typing import Any

from cogant.reverse.parser import ReverseGNNModel

__all__ = ['MatrixFunctions', 'make_matrix_functions']

class MatrixFunctions:
    A: Any
    B: Any
    C: Any
    D: Any
    def __init__(self, model: ReverseGNNModel) -> None: ...
    def likelihood(self, state_dist: list[float]) -> list[float]: ...
    def transition(self, state_dist: list[float], action: int = 0) -> list[float]: ...
    def preference_score(self, obs_dist: list[float]) -> float: ...
    def prior(self) -> list[float]: ...
    def expected_free_energy(self, state_dist: list[float], action: int) -> float: ...
    def best_action(self, state_dist: list[float]) -> int: ...
    @classmethod
    def from_gnn_text(cls, gnn_text: str) -> MatrixFunctions: ...

def make_matrix_functions(model: ReverseGNNModel) -> MatrixFunctions: ...
