from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

__all__ = ['IdempotencyReport', 'RoundtripResult', 'verify_roundtrip', 'verify_repo_roundtrip', 'ROLE_MATCH_THRESHOLD', 'check_structural_idempotency', 'check_semantic_idempotency']

ROLE_MATCH_THRESHOLD: float

@dataclass
class IdempotencyReport:
    is_idempotent: bool = ...
    forward_roles: dict[str, int] = field(default_factory=dict)
    reverse_roles: dict[str, int] = field(default_factory=dict)
    differences: list[str] = field(default_factory=list)
    score: float = ...

@dataclass
class RoundtripResult:
    is_isomorphic: bool = ...
    role_match_score: float = ...
    matrix_score: float = ...
    structural_score: float = ...
    original_roles: dict[str, int] = field(default_factory=dict)
    synthesized_roles: dict[str, int] = field(default_factory=dict)
    shape_match: dict[str, bool] = field(default_factory=dict)
    package_path: Path | None = ...
    errors: list[str] = field(default_factory=list)
    def summary(self) -> str: ...

def check_structural_idempotency(original_graph: Any, roundtrip_graph: Any) -> IdempotencyReport: ...
def check_semantic_idempotency(original_mappings: dict[str, Any], roundtrip_mappings: dict[str, Any]) -> IdempotencyReport: ...
def verify_roundtrip(gnn_path: str | Path, tmp_dir: str | Path | None = None, *, role_threshold: float = ..., keep_tmp: bool = False) -> RoundtripResult: ...
def verify_repo_roundtrip(repo_path: str | Path, output_dir: str | Path | None = None, *, role_threshold: float = ...) -> RoundtripResult: ...
