from dataclasses import dataclass, field
from pathlib import Path

__all__ = ['RoundtripResult', 'verify_roundtrip', 'verify_repo_roundtrip', 'ROLE_MATCH_THRESHOLD']

ROLE_MATCH_THRESHOLD: float

@dataclass
class RoundtripResult:
    is_isomorphic: bool = ...
    role_match_score: float = ...
    matrix_score: float = ...
    structural_score: float = ...
    original_roles: dict[str, int] = field(default_factory=dict)
    synthesized_roles: dict[str, int] = field(default_factory=dict)
    shape_match: dict[str, bool] = field(default_factory=dict)
    package_path: Path | None = ...
    errors: list[str] = field(default_factory=list)
    def summary(self) -> str: ...

def verify_roundtrip(gnn_path: str | Path, tmp_dir: str | Path | None = None, *, role_threshold: float = ..., keep_tmp: bool = False) -> RoundtripResult: ...
def verify_repo_roundtrip(repo_path: str | Path, output_dir: str | Path | None = None, *, role_threshold: float = ...) -> RoundtripResult: ...
