from dataclasses import dataclass, field

from cogant.reverse.parser import ReverseGNNModel

__all__ = ["NodePlan", "PackagePlan", "plan_package"]

@dataclass
class NodePlan:
    slot: str = ...
    name: str = ...
    role: str = ...
    python_type: str = ...
    module: str = ...
    cardinality: int = ...
    initial_value: str = ...

@dataclass
class PackagePlan:
    package_name: str = ...
    raw_model_name: str = ...
    nodes: list[NodePlan] = field(default_factory=list)
    state_vars: list[NodePlan] = field(default_factory=list)
    obs_functions: list[NodePlan] = field(default_factory=list)
    action_methods: list[NodePlan] = field(default_factory=list)
    policy_functions: list[NodePlan] = field(default_factory=list)
    constraint_checks: list[NodePlan] = field(default_factory=list)
    context_functions: list[NodePlan] = field(default_factory=list)
    scaffold_constraint_checks: list[NodePlan] = field(default_factory=list)
    scaffold_policy_functions: list[NodePlan] = field(default_factory=list)
    scaffold_context_classes: list[NodePlan] = field(default_factory=list)
    has_A_matrix: bool = ...
    has_B_tensor: bool = ...
    has_C_vector: bool = ...
    has_D_vector: bool = ...
    def validate(self) -> list[str]: ...
    def diff(self, other: PackagePlan) -> str: ...
    def to_json(self) -> str: ...
    @classmethod
    def from_json(cls, data: str) -> PackagePlan: ...

def plan_package(model: ReverseGNNModel) -> PackagePlan: ...
