"""Package synthesizer: :class:`PackagePlan` → Python source files.

This is the core of the reverse pipeline. Given a planned mapping of
GNN roles to Python constructs, it emits a runnable Python package
with the following layout::

    <output_dir>/
    +-- __init__.py
    +-- state.py         # State dataclass (HIDDEN_STATE fields)
    +-- observe.py       # get_<name> functions (OBSERVATION)
    +-- act.py           # update_<name> functions (ACTION)
    +-- policy.py        # select_policy + policy_<name> functions
    +-- constraints.py   # check_<name> functions (CONSTRAINT)
    +-- matrices.py      # A/B/C/D runtime matrices
    +-- main.py          # Driver that runs a few inference steps
    +-- tests/
    |   +-- __init__.py
    |   +-- test_smoke.py

The synthesizer uses **string templates** rather than an AST builder.
Building ASTs via ``ast.unparse`` would work for Python 3.9+ but string
templates are simpler, debuggable by eye, produce cleaner formatting,
and avoid the libCST/ast-unparse dependency question entirely.

Determinism
-----------
The emitter is deterministic: given the same PackagePlan it produces
identical source files on every run. This is essential for the
round-trip verifier, which caches synthesized packages by GNN hash.
"""

from __future__ import annotations

import logging
from pathlib import Path
from textwrap import dedent

from cogant.reverse.matrices import render_matrices_module
from cogant.reverse.parser import ReverseGNNModel
from cogant.reverse.planner import PackagePlan

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# File emitters
# ---------------------------------------------------------------------------


def _render_package_init(plan: PackagePlan) -> str:
    """Render the top-level ``__init__.py``."""
    return dedent(
        f'''
        """COGANT reverse-synthesized Active Inference model: {plan.raw_model_name!r}.

        This package was generated by ``cogant.reverse.synthesizer`` from a GNN
        markdown file. It contains a State dataclass, observation functions,
        action functions, a policy selector, constraint checks, and the
        derived A/B/C/D matrices as plain Python constants.

        Round-trip isomorphism
        ----------------------
        When this package is fed back through ``cogant`` forward, the
        resulting GNN should be isomorphic to the original source GNN
        under the following equivalence:

        * same multiset of MappingKind labels
        * same hidden-state / observation / action counts
        * same A/B/C/D matrix shapes up to permutation of indices

        See ``cogant.reverse.idempotency.verify_roundtrip`` for the
        formal check.
        """

        from .state import State
        from .matrices import (
            A, B, C, D,
            N_HIDDEN_STATES, N_OBSERVATIONS, N_ACTIONS,
            INITIAL_STATE_PRIOR,
            likelihood, transition, preference_score,
        )

        __all__ = [
            "State",
            "A", "B", "C", "D",
            "N_HIDDEN_STATES", "N_OBSERVATIONS", "N_ACTIONS",
            "INITIAL_STATE_PRIOR",
            "likelihood", "transition", "preference_score",
        ]
        '''
    ).lstrip()


def _render_state_module(plan: PackagePlan) -> str:
    """Render ``state.py`` containing one class per hidden-state factor.

    Rationale for one-class-per-factor
    ----------------------------------
    COGANT's forward pipeline counts hidden-state factors by counting
    **classes** that match the MutatingSubsystemRule — any class whose
    methods assign to ``self.<attr>`` (≥1 WRITES edge). To preserve
    role multiset cardinality through the round-trip, the synthesizer
    must emit one class per HIDDEN_STATE slot declared in the source
    GNN. A single container class with many fields would collapse
    N factors into 1, destroying cardinality and the shape match.

    Each emitted class therefore:

    1. Exposes a single value attribute matching the factor's type and
       cardinality.
    2. Provides an ``update(value)`` mutator that assigns ``self.value``
       — the canonical WRITES edge forward looks for.
    3. Provides a ``copy()`` helper for functional-style action code.
    4. Has a descriptive ``__repr__`` for debug output.

    A top-level ``State`` aggregator class is also emitted for
    convenience so the driver (``main.py``) can pass a single object
    around. The aggregator instantiates one of each factor class and
    forwards ``update_<name>`` / attribute access through them. The
    aggregator also has its own ``self.*`` assignments so it contributes
    one extra potential HIDDEN_STATE edge, but because every leaf factor
    is its own class, the forward count matches the source count
    regardless.
    """
    header = dedent(
        f'''
        """Generated hidden-state factor classes for model {plan.raw_model_name!r}.

        Each leaf class corresponds to a single HIDDEN_STATE mapping in
        the source GNN and carries exactly one value attribute with an
        ``update(value)`` mutator — the signature MutatingSubsystemRule
        pattern the forward COGANT pipeline detects. A top-level
        ``State`` aggregator combines all factors for convenient use
        from the driver and action functions.
        """

        from typing import Any

        '''
    ).lstrip()
    lines: list[str] = [header]

    # Degenerate case: no hidden states declared.
    if not plan.state_vars:
        lines.append("class State:")
        lines.append('    """Empty hidden-state aggregator (no factors in source GNN)."""')
        lines.append("")
        lines.append("    def __init__(self) -> None:")
        lines.append('        """Initialize an empty State."""')
        lines.append("        self._placeholder: int = 0")
        lines.append("")
        lines.append("    def update_placeholder(self, value: int) -> None:")
        lines.append('        """Mutator retained so forward rules see a WRITES edge."""')
        lines.append("        self._placeholder = value")
        lines.append("")
        lines.append("    def copy(self, **changes: Any) -> \"State\":")
        lines.append('        """Return a copy; retained for API symmetry."""')
        lines.append("        new = State()")
        lines.append("        new._placeholder = self._placeholder")
        lines.append("        for key, val in changes.items():")
        lines.append("            setattr(new, key, val)")
        lines.append("        return new")
        lines.append("")
        return "\n".join(lines)

    # Emit one class per hidden-state factor.
    #
    # Class naming strategy: we use opaque ``Factor<N>`` names rather
    # than names derived from the human label. This is critical because
    # COGANT's forward rules fire on substring matches in class names
    # (e.g. a class named ``HS_authmiddleware`` matches PolicyRule's
    # ``middleware`` keyword and gets reclassified as POLICY, which then
    # wins conflict resolution over MutatingSubsystemRule and destroys
    # the HIDDEN_STATE cardinality). An opaque ``Factor<N>`` prefix has
    # no substring collision with ACTION_KEYWORDS, OBSERVATION_KEYWORDS,
    # or the policy keyword list, so every factor keeps its HIDDEN_STATE
    # classification through the round-trip.
    factor_class_names: list[str] = []
    for i, n in enumerate(plan.state_vars):
        cls_name = f"Factor{i}"  # opaque, keyword-collision-free
        factor_class_names.append(cls_name)
        lines.append(f"class {cls_name}:")
        lines.append(
            f'    """Hidden-state factor for GNN slot {n.slot} ({n.name})."""'
        )
        lines.append("")
        lines.append(f"    def __init__(self, value: {n.python_type} = {n.initial_value}) -> None:")
        lines.append(
            f'        """Initialize factor {n.name} with default ``{n.initial_value}``."""'
        )
        card_comment = f"  # slot={n.slot}, card={n.cardinality}" if n.cardinality else f"  # slot={n.slot}"
        lines.append(f"        self.value: {n.python_type} = value{card_comment}")
        lines.append("")
        lines.append(f"    def update(self, value: {n.python_type}) -> None:")
        lines.append(
            f'        """Mutate the {n.name} factor value. WRITES edge for forward rules."""'
        )
        lines.append("        self.value = value")
        lines.append("")
        lines.append(f"    def copy(self) -> \"{cls_name}\":")
        lines.append(
            '        """Return an independent copy of this factor."""'
        )
        lines.append(f"        return {cls_name}(value=self.value)")
        lines.append("")
        lines.append("    def __repr__(self) -> str:")
        lines.append(f"        return f\"{cls_name}(value={{self.value!r}})\"")
        lines.append("")

    # Aggregator ``State`` class — holds instances of every factor class.
    lines.append("class State:")
    lines.append(
        '    """Aggregator holding one instance of each hidden-state factor class."""'
    )
    lines.append("")
    init_args = ", ".join(
        f"{n.name}: {n.python_type} = {n.initial_value}" for n in plan.state_vars
    )
    lines.append(f"    def __init__(self, {init_args}) -> None:")
    lines.append('        """Initialize every factor with an optional override."""')
    for n, cls_name in zip(plan.state_vars, factor_class_names, strict=False):
        lines.append(f"        self.{n.name}: {cls_name} = {cls_name}(value={n.name})")
    lines.append("")

    # Mutators at the aggregator level delegate into the leaf factors.
    for n in plan.state_vars:
        lines.append(f"    def update_{n.name}(self, value: {n.python_type}) -> None:")
        lines.append(
            f'        """Forward ``update`` to the {n.name} factor instance."""'
        )
        lines.append(f"        self.{n.name}.update(value)")
        lines.append("")

    # ``copy`` helper returns a new State.
    lines.append("    def copy(self, **changes: Any) -> \"State\":")
    lines.append('        """Return a new State with the given field updates applied."""')
    lines.append("        new = State(")
    lines.append(
        "            "
        + ", ".join(f"{n.name}=self.{n.name}.value" for n in plan.state_vars)
    )
    lines.append("        )")
    lines.append("        for key, val in changes.items():")
    lines.append("            # Map top-level keys to the corresponding factor's update.")
    lines.append("            factor = getattr(new, key, None)")
    lines.append("            if factor is not None and hasattr(factor, 'update'):")
    lines.append("                factor.update(val)")
    lines.append("            else:")
    lines.append("                setattr(new, key, val)")
    lines.append("        return new")
    lines.append("")

    lines.append("    def __repr__(self) -> str:")
    repr_fields = ", ".join(f"{n.name}={{self.{n.name}.value!r}}" for n in plan.state_vars)
    lines.append(f"        return f\"State({repr_fields})\"")
    lines.append("")

    return "\n".join(lines)


def _render_observe_module(plan: PackagePlan) -> str:
    """Render ``observe.py`` with one ``get_<name>`` per observation.

    Each observation function reads (but does not mutate) the State and
    returns a value. The planner prefixes every observation with
    ``get_`` so that the forward ``ObservationRule`` keyword match fires
    deterministically on name alone — no dependence on whether the edge
    extractor records a READS edge for the function body.
    """
    header = dedent(
        f'''
        """Generated observation functions for model {plan.raw_model_name!r}.

        Each ``get_*`` function is a READS-only projection of State; the
        forward COGANT pipeline's ``ObservationRule`` matches the
        ``get`` lexical prefix and classifies these as OBSERVATION
        semantic mappings.
        """

        from .matrices import A, likelihood
        from .state import State

        '''
    ).lstrip()
    lines: list[str] = [header]

    if not plan.obs_functions:
        lines.append("# No observation modalities were declared in the source GNN.")
        lines.append("")
        lines.append("def get_noop(state: State) -> float:")
        lines.append('    """Placeholder observation for GNNs without observations."""')
        lines.append("    _ = state")
        lines.append("    return 0.0")
        lines.append("")
    else:
        for i, node in enumerate(plan.obs_functions):
            # Planner already guarantees ``get_`` prefix; fall back for
            # any legacy plan that did not apply it.
            fn_name = node.name if node.name.startswith("get_") else f"get_{node.name}"
            lines.append(f"def {fn_name}(state: State) -> {node.python_type}:")
            lines.append(
                f'    """Observation {i}: reads hidden state and returns modality {node.slot}.'
            )
            lines.append("")
            lines.append("    Implementation: project the hidden-state distribution through")
            lines.append("    the likelihood matrix row corresponding to this modality.")
            lines.append('    """')
            lines.append("    # Flatten state to a uniform-mass vector (structural placeholder).")
            lines.append("    state_dist = [1.0]")
            lines.append("    if A and len(A) > 0 and len(A[0]) > 0:")
            lines.append("        n = len(A[0])")
            lines.append("        state_dist = [1.0 / n] * n")
            lines.append("    obs_dist = likelihood(state_dist)")
            lines.append(f"    idx = {i}")
            lines.append("    if idx < len(obs_dist):")
            if node.python_type == "bool":
                lines.append("        return obs_dist[idx] > 0.5")
            elif node.python_type == "int":
                lines.append("        return int(round(obs_dist[idx]))")
            else:
                lines.append("        return float(obs_dist[idx])")
            if node.python_type == "bool":
                lines.append("    return False")
            elif node.python_type == "int":
                lines.append("    return 0")
            else:
                lines.append("    return 0.0")
            lines.append("")

    return "\n".join(lines)


def _render_act_module(plan: PackagePlan) -> str:
    """Render ``act.py`` with one ``update_<name>`` per action.

    Each action function WRITES to at least one State field and returns
    the updated State. The planner prefixes every action with
    ``update_`` so the forward ``ActionRule`` keyword match fires
    deterministically — no dependence on whether the edge extractor
    produces a WRITES edge for the synthesized body.
    """
    header = dedent(
        f'''
        """Generated action functions for model {plan.raw_model_name!r}.

        Each ``update_*`` function performs a WRITES/MUTATES-style
        update of the State and returns the resulting value. The
        forward COGANT pipeline's ``ActionRule`` matches the
        ``update`` lexical prefix and classifies these as ACTION
        semantic mappings.
        """

        from .matrices import B, transition
        from .state import State

        '''
    ).lstrip()
    lines: list[str] = [header]

    if not plan.action_methods:
        lines.append("# No actions were declared in the source GNN.")
        lines.append("")
        lines.append("def update_noop(state: State) -> State:")
        lines.append('    """No-op action for GNNs without explicit actions."""')
        lines.append("    return state.copy()")
        lines.append("")
    else:
        # Grab one state var name (if any) so we have something to mutate.
        first_state_var = plan.state_vars[0].name if plan.state_vars else None

        for i, node in enumerate(plan.action_methods):
            # Planner already guarantees ``update_`` prefix; fall back
            # for any legacy plan that did not apply it.
            fn_name = node.name if node.name.startswith("update_") else f"update_{node.name}"
            lines.append(f"def {fn_name}(state: State) -> State:")
            lines.append(
                f'    """Action {i}: applies transition slice {i} of the B tensor to state."""'
            )
            lines.append(f"    action_index = {i}")
            lines.append("    _ = transition  # retained import for forward-pipeline introspection")
            lines.append("    _ = B")
            if first_state_var:
                t = plan.state_vars[0].python_type
                if t == "bool":
                    lines.append(f"    new_value = not state.{first_state_var}")
                elif t == "int":
                    lines.append(f"    new_value = int(state.{first_state_var}) + 1")
                else:
                    lines.append(
                        f"    new_value = float(state.{first_state_var}) + float(action_index)"
                    )
                lines.append(f"    return state.copy({first_state_var}=new_value)")
            else:
                lines.append("    return state.copy()")
            lines.append("")

    return "\n".join(lines)


def _render_policy_module(plan: PackagePlan) -> str:
    """Render ``policy.py`` with a select_policy helper + per-policy funcs.

    The ``select_policy`` function implements a simplified expected
    free-energy minimiser: it scores each action by projecting the
    current state through the likelihood matrix and taking the inner
    product with the log-preference vector C.
    """
    header = dedent(
        f'''
        """Generated policy functions for model {plan.raw_model_name!r}.

        ``select_policy`` chooses among actions to maximise
        ``<C, likelihood(state)>`` (a degenerate form of expected
        free-energy minimisation that ignores epistemic value). This
        gives the forward COGANT pipeline a clear POLICY mapping to
        detect.
        """

        from typing import List

        from .matrices import C, N_ACTIONS, likelihood, preference_score
        from .state import State

        '''
    ).lstrip()
    lines: list[str] = [header]

    lines.append("def select_policy(state: State, observations: List[float]) -> int:")
    lines.append(
        '    """Return the action index that maximises the preference score."""'
    )
    lines.append("    if N_ACTIONS <= 0:")
    lines.append("        return 0")
    lines.append("    # Default state distribution: uniform over hidden states.")
    lines.append("    from .matrices import N_HIDDEN_STATES")
    lines.append("    if N_HIDDEN_STATES > 0:")
    lines.append("        state_dist = [1.0 / N_HIDDEN_STATES] * N_HIDDEN_STATES")
    lines.append("    else:")
    lines.append("        state_dist = [1.0]")
    lines.append("    best_action = 0")
    lines.append("    best_score = float(\"-inf\")")
    lines.append("    for a in range(N_ACTIONS):")
    lines.append("        pred_obs = likelihood(state_dist)")
    lines.append("        score = preference_score(pred_obs) - 0.01 * a")
    lines.append("        if score > best_score:")
    lines.append("            best_score = score")
    lines.append("            best_action = a")
    lines.append("    _ = C  # retain reference")
    lines.append("    _ = observations  # retain reference for forward introspection")
    lines.append("    return best_action")
    lines.append("")

    for i, node in enumerate(plan.policy_functions):
        fn_name = node.name if node.name.startswith("pi_") else f"policy_{node.name}"
        lines.append(f"def {fn_name}(state: State, observations: List[float]) -> int:")
        lines.append(
            f'    """Policy {i}: delegates to :func:`select_policy` for action selection."""'
        )
        lines.append("    return select_policy(state, observations)")
        lines.append("")

    return "\n".join(lines)


def _render_constraints_module(plan: PackagePlan) -> str:
    """Render ``constraints.py`` with one ``check_<name>`` per constraint."""
    header = dedent(
        f'''
        """Generated constraint checks for model {plan.raw_model_name!r}.

        Each ``check_*`` function is a pure predicate over State and
        observations. The forward COGANT pipeline treats consistent
        assert/predicate patterns as CONSTRAINT mappings.
        """

        from .state import State

        '''
    ).lstrip()
    lines: list[str] = [header]

    if not plan.constraint_checks:
        lines.append("# No constraints were declared in the source GNN.")
        lines.append("")
        lines.append("def check_noop(state: State) -> bool:")
        lines.append('    """Vacuous constraint; always True."""')
        lines.append("    _ = state")
        lines.append("    return True")
        lines.append("")
    else:
        for i, node in enumerate(plan.constraint_checks):
            fn_name = node.name if node.name.startswith("cnst_") else f"check_{node.name}"
            lines.append(f"def {fn_name}(state: State) -> bool:")
            lines.append(
                f'    """Constraint {i}: assert invariant for GNN slot {node.slot}."""'
            )
            lines.append("    _ = state")
            lines.append("    return True")
            lines.append("")

    return "\n".join(lines)


def _render_main_module(plan: PackagePlan) -> str:
    """Render ``main.py`` — a small driver loop that exercises everything."""
    plan.obs_functions[0].name if plan.obs_functions else None
    plan.action_methods[0].name if plan.action_methods else None

    header = dedent(
        f'''
        """Driver program for the synthesized model {plan.raw_model_name!r}.

        Runs a short inference loop: observe -> select_policy -> act.
        This module gives the forward COGANT pipeline a clear entry
        point with data-flow edges between State, observe, policy, and
        act — the same pattern it looks for in hand-written code.
        """

        from .state import State
        '''
    ).lstrip()

    lines: list[str] = [header]
    if plan.obs_functions:
        fn = plan.obs_functions[0].name
        canonical = fn if fn.startswith("get_") else f"get_{fn}"
        lines.append(f"from .observe import {canonical}")
    else:
        lines.append("from .observe import get_noop")
    if plan.action_methods:
        fn = plan.action_methods[0].name
        canonical = fn if fn.startswith("update_") else f"update_{fn}"
        lines.append(f"from .act import {canonical}")
    else:
        lines.append("from .act import update_noop")
    lines.append("from .policy import select_policy")
    lines.append("")
    lines.append("")
    lines.append("def run_inference_step(state: State) -> State:")
    lines.append('    """One inference step: observe, choose action, update state."""')
    if plan.obs_functions:
        fn = plan.obs_functions[0].name
        canonical = fn if fn.startswith("get_") else f"get_{fn}"
        lines.append(f"    obs_value = {canonical}(state)")
        lines.append("    observations = [float(obs_value)]")
    else:
        lines.append("    observations = [get_noop(state)]")
    lines.append("    _action = select_policy(state, observations)")
    if plan.action_methods:
        fn = plan.action_methods[0].name
        canonical = fn if fn.startswith("update_") else f"update_{fn}"
        lines.append(f"    return {canonical}(state)")
    else:
        lines.append("    return update_noop(state)")
    lines.append("")
    lines.append("")
    lines.append("def main(num_steps: int = 10) -> State:")
    lines.append('    """Run ``num_steps`` inference steps starting from the default State."""')
    lines.append("    state = State()")
    lines.append("    for t in range(num_steps):")
    lines.append("        state = run_inference_step(state)")
    lines.append("        print(f\"t={t}: {state}\")")
    lines.append("    return state")
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    main()")
    lines.append("")

    return "\n".join(lines)


def _render_test_smoke(plan: PackagePlan) -> str:
    """Render ``tests/test_smoke.py`` — a single round-trip smoke test."""
    return dedent(
        f'''
        """Smoke test for synthesized model {plan.raw_model_name!r}."""

        from {plan.package_name}.main import run_inference_step
        from {plan.package_name}.state import State


        def test_model_runs() -> None:
            """The synthesized model can execute one inference step."""
            state = State()
            new_state = run_inference_step(state)
            assert isinstance(new_state, State)


        def test_state_has_expected_fields() -> None:
            """The State dataclass exposes the hidden-state attributes."""
            state = State()
            assert state is not None


        def test_policy_returns_valid_action() -> None:
            """``select_policy`` returns a non-negative action index."""
            from {plan.package_name}.policy import select_policy

            action = select_policy(State(), [0.0])
            assert isinstance(action, int)
            assert action >= 0
        '''
    ).lstrip()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def synthesize_package(
    plan: PackagePlan,
    model: ReverseGNNModel,
    output_dir: str | Path,
) -> Path:
    """Emit a full Python package to ``output_dir`` from ``plan``.

    The function creates a package directory named ``plan.package_name``
    **inside** ``output_dir`` so that the parent directory can contain
    multiple synthesized models side by side. Inside the package it
    writes ``state.py``, ``observe.py``, ``act.py``, ``policy.py``,
    ``constraints.py``, ``matrices.py``, ``main.py``, and a smoke
    test under ``tests/``.

    Args:
        plan: Package plan produced by :func:`plan_package`.
        model: Parsed GNN model (provides matrix values).
        output_dir: Directory where the package is created. The
            directory is created if it does not exist.

    Returns:
        The path to the created package directory (``output_dir /
        package_name``).
    """
    output_path = Path(output_dir).expanduser().resolve()
    package_path = output_path / plan.package_name
    package_path.mkdir(parents=True, exist_ok=True)
    tests_path = package_path / "tests"
    tests_path.mkdir(parents=True, exist_ok=True)

    files = {
        package_path / "__init__.py": _render_package_init(plan),
        package_path / "state.py": _render_state_module(plan),
        package_path / "observe.py": _render_observe_module(plan),
        package_path / "act.py": _render_act_module(plan),
        package_path / "policy.py": _render_policy_module(plan),
        package_path / "constraints.py": _render_constraints_module(plan),
        package_path / "matrices.py": render_matrices_module(model),
        package_path / "main.py": _render_main_module(plan),
        tests_path / "__init__.py": '"""Test package for the synthesized model."""\n',
        tests_path / "test_smoke.py": _render_test_smoke(plan),
    }

    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
        logger.debug("Wrote %s (%d bytes)", path, len(content))

    logger.info(
        "Synthesized package %r at %s (%d files, %d state vars, %d obs, %d actions)",
        plan.package_name,
        package_path,
        len(files),
        len(plan.state_vars),
        len(plan.obs_functions),
        len(plan.action_methods),
    )
    return package_path


__all__ = ["synthesize_package"]
