from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path

@dataclass
class CodeMetrics:
    lines_of_code: int
    logical_lines: int
    comment_lines: int
    blank_lines: int
    docstring_coverage: float
    public_symbols: int
    documented_symbols: int

@dataclass
class HalsteadMetrics:
    unique_operators: int
    unique_operands: int
    total_operators: int
    total_operands: int
    vocabulary: int
    length: int
    volume: float
    difficulty: float
    effort: float
    @classmethod
    def compute(cls, source: str) -> HalsteadMetrics: ...

class HalsteadVisitor(ast.NodeVisitor):
    operators: list[str]
    operands: list[str]
    def __init__(self) -> None: ...
    def visit_BinOp(self, node: ast.BinOp) -> None: ...
    def visit_UnaryOp(self, node: ast.UnaryOp) -> None: ...
    def visit_BoolOp(self, node: ast.BoolOp) -> None: ...
    def visit_Compare(self, node: ast.Compare) -> None: ...
    def visit_Assign(self, node: ast.Assign) -> None: ...
    def visit_AugAssign(self, node: ast.AugAssign) -> None: ...
    def visit_Call(self, node: ast.Call) -> None: ...
    def visit_Name(self, node: ast.Name) -> None: ...
    def visit_Constant(self, node: ast.Constant) -> None: ...
    def visit_Attribute(self, node: ast.Attribute) -> None: ...
    def get_metrics(self) -> HalsteadMetrics: ...

class MetricsAnalyzer:
    def __init__(self) -> None: ...
    def compute(self, source: str) -> CodeMetrics: ...
    def halstead(self, source: str) -> HalsteadMetrics: ...
    def analyze_file(self, file_path: Path) -> tuple[CodeMetrics, HalsteadMetrics]: ...

class DocstringVisitor(ast.NodeVisitor):
    public_symbols: int
    documented_symbols: int
    current_class: str | None
    def __init__(self) -> None: ...
    def visit_FunctionDef(self, node: ast.FunctionDef) -> None: ...
    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None: ...
    def visit_ClassDef(self, node: ast.ClassDef) -> None: ...
