from _typeshed import Incomplete
from typing import Any

logger: Incomplete

class CoverageIngester:
    coverage_data: dict[str, Any]
    def __init__(self) -> None: ...
    def ingest_coverage_xml(self, xml_path: str) -> dict[str, Any]: ...
    def ingest_coverage_py(self, coverage_file: str) -> dict[str, Any]: ...
    def map_coverage_to_spans(self) -> list[dict[str, Any]]: ...
    def get_coverage_summary(self) -> dict[str, Any]: ...
    def get_file_coverage(self, filepath: str) -> dict[str, Any] | None: ...
