from typing import Any

from _typeshed import Incomplete as Incomplete

logger: Incomplete

class TraceIngester:
    traces: list[dict[str, Any]]
    call_graph: dict[str, list[str]]
    def __init__(self) -> None: ...
    def ingest_chrome_trace(self, json_path: str) -> list[dict[str, Any]]: ...
    def ingest_custom_trace(self, trace_path: str, format: str) -> list[dict[str, Any]]: ...
    def extract_call_sequences(self) -> list[list[str]]: ...
    def extract_call_graph(self) -> dict[str, list[str]]: ...
    def extract_timing(self) -> dict[str, dict[str, float]]: ...
    def extract_hot_paths(self, count: int = 10) -> list[tuple[list[str], int]]: ...
    def get_trace_summary(self) -> dict[str, Any]: ...
    def get_function_calls(self, function_name: str) -> list[dict[str, Any]]: ...
    def get_caller_functions(self, function_name: str) -> list[str]: ...
    def get_callee_functions(self, function_name: str) -> list[str]: ...
