from pathlib import Path
from typing import Any

from cogant.schemas.graph import ProgramGraph

__all__: list[str]

def load_program_graph(target: Path) -> ProgramGraph: ...
def run_static_analysis(
    path: Path, *, output: Path | None = ..., hotspot_threshold: int = ...
) -> dict[str, Any]: ...
def run_graph_analysis(path_or_bundle: Path, *, output: Path | None = ...) -> dict[str, Any]: ...
def run_visualize(path_or_run_dir: Path, *, output: Path, fmt: str = ...) -> Path: ...
def run_multi_export(
    path_or_bundle: Path, *, formats: list[str], output_dir: Path
) -> dict[str, Any]: ...
