from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Any

class ArtifactKey(StrEnum):
    REPO_SNAPSHOT = 'repo_snapshot'
    PARSED_MODULES = 'parsed_modules_detail'
    NORMALIZED_FACTS = 'normalized_facts'
    PROGRAM_GRAPH = '_program_graph'
    SEMANTIC_MAPPINGS = '_semantic_mappings'
    TRANSLATION_ENGINE = '_translation_engine'
    STATE_SPACE_MODEL = '_state_space_model'
    PROCESS_MODEL = '_process_model'
    EXPORT_PATHS = 'export_paths'

@dataclass
class Bundle:
    target: str
    artifacts: dict[str, Any] = field(default_factory=dict)
    stage_results: dict[str, dict[str, Any]] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    def get_artifact(self, key: str, required: bool = False) -> Any: ...
    def repo_summary(self) -> dict[str, Any]: ...
    def program_graph(self) -> dict[str, Any]: ...
    def state_space_model(self) -> dict[str, Any]: ...
    def process_model(self) -> dict[str, Any]: ...
    def gnn_markdown(self) -> str: ...
    def validation_report(self) -> dict[str, Any]: ...
    def render_site(self, output_dir: str) -> Path: ...
    def to_json(self) -> str: ...
    def save_json(self, path: str) -> None: ...
