from collections.abc import AsyncGenerator
from pathlib import Path
from typing import Any

from cogant.api.bundle import Bundle
from cogant.schemas.graph import ProgramGraph as ProgramGraph

def program_graph_to_dict(
    pg: ProgramGraph, statistics: dict[str, Any] | None = None
) -> dict[str, Any]: ...
def run_ingest(bundle_target: str, bundle: Any) -> dict[str, Any]: ...
def run_static(bundle: Any) -> dict[str, Any]: ...
def run_normalize(bundle: Any) -> dict[str, Any]: ...
def run_graph(bundle: Any, target: str) -> dict[str, Any]: ...
def run_translate(bundle: Any, *, min_confidence: float = ...) -> dict[str, Any]: ...
def run_statespace(bundle: Any, target: str) -> dict[str, Any]: ...
def run_process(bundle: Any, target: str) -> dict[str, Any]: ...
def run_export(
    bundle: Any, output_dir: str, *, render_visualizations: bool = ...
) -> dict[str, Any]: ...
def run_validate(
    bundle: Any,
    *,
    upstream_gnn: bool | None = ...,
    upstream_pipeline: bool = ...,
    upstream_pipeline_output_dir: Path | None = ...,
    upstream_pipeline_only_steps: list[int] | None = ...,
    upstream_pipeline_skip_steps: list[int] | None = ...,
    upstream_pipeline_frameworks: str = ...,
    upstream_pipeline_llm_model: str | None = ...,
) -> dict[str, Any]: ...
def run_dynamic(
    bundle: Any, coverage_path: str | None = None, trace_path: str | None = None
) -> dict[str, Any]: ...
def translate_source(
    language: str, source_code: str, *, stages: list[str] | None = ...
) -> Bundle: ...
async def translate_stream(
    sources: list[tuple[str, str]], options: dict[str, Any] | None = ...
) -> AsyncGenerator[dict[str, Any]]: ...
def translate_batch(requests: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
