from typing import Any

from cogant.schemas.graph import ProgramGraph as ProgramGraph

def program_graph_to_dict(pg: ProgramGraph, statistics: dict[str, Any] | None = None) -> dict[str, Any]: ...
def run_ingest(bundle_target: str, bundle: Any) -> dict[str, Any]: ...
def run_static(bundle: Any) -> dict[str, Any]: ...
def run_normalize(bundle: Any) -> dict[str, Any]: ...
def run_graph(bundle: Any, target: str) -> dict[str, Any]: ...
def run_translate(bundle: Any) -> dict[str, Any]: ...
def run_statespace(bundle: Any, target: str) -> dict[str, Any]: ...
def run_process(bundle: Any, target: str) -> dict[str, Any]: ...
def run_export(bundle: Any, output_dir: str) -> dict[str, Any]: ...
def run_validate(bundle: Any) -> dict[str, Any]: ...
def run_dynamic(bundle: Any, coverage_path: str | None = None, trace_path: str | None = None) -> dict[str, Any]: ...
