from _typeshed import Incomplete
from cogant.graph.builder import ProgramGraphBuilder as ProgramGraphBuilder
from cogant.ingest.repo import RepoIngester as RepoIngester, RepoSnapshot as RepoSnapshot
from cogant.normalize.canonical import CanonicalNormalizer as CanonicalNormalizer, LanguageFact as LanguageFact
from cogant.process.extractor import ProcessExtractor as ProcessExtractor
from cogant.schemas.core import EdgeKind as EdgeKind, NodeKind as NodeKind
from cogant.schemas.graph import ProgramGraph as ProgramGraph
from cogant.schemas.semantic import SemanticMapping as SemanticMapping
from cogant.statespace.compiler import StateSpaceCompiler as StateSpaceCompiler
from cogant.static.parser import PythonASTParser as PythonASTParser
from cogant.translate.confidence import ConfidenceModel as ConfidenceModel
from cogant.translate.engine import TranslationEngine as TranslationEngine
from cogant.translate.review import ReviewManager as ReviewManager
from cogant.translate.rules import ActionRule as ActionRule, CircuitBreakerRule as CircuitBreakerRule, ConfigRule as ConfigRule, ContainmentRule as ContainmentRule, ContextRule as ContextRule, DataPipelineRule as DataPipelineRule, ErrorBoundaryRule as ErrorBoundaryRule, EventBusRule as EventBusRule, FeatureFlagRule as FeatureFlagRule, InheritanceRule as InheritanceRule, MutatingSubsystemRule as MutatingSubsystemRule, ObservationRule as ObservationRule, OrchestratorRule as OrchestratorRule, PolicyRule as PolicyRule, PreferenceRule as PreferenceRule, ReadOnlyInputRule as ReadOnlyInputRule, RetryPatternRule as RetryPatternRule, SingletonAccessRule as SingletonAccessRule, TestAssertionRule as TestAssertionRule
from cogant.validate.schema_check import SchemaValidator as SchemaValidator
from typing import Any

logger: Incomplete

def program_graph_to_dict(pg: ProgramGraph, statistics: dict[str, Any] | None = None) -> dict[str, Any]: ...
def run_ingest(bundle_target: str, bundle: Any) -> dict[str, Any]: ...
def run_static(bundle: Any) -> dict[str, Any]: ...
def run_normalize(bundle: Any) -> dict[str, Any]: ...
def run_graph(bundle: Any, target: str) -> dict[str, Any]: ...
def run_translate(bundle: Any) -> dict[str, Any]: ...
def run_statespace(bundle: Any, target: str) -> dict[str, Any]: ...
def run_process(bundle: Any, target: str) -> dict[str, Any]: ...
def run_export(bundle: Any, output_dir: str) -> dict[str, Any]: ...
def run_validate(bundle: Any) -> dict[str, Any]: ...
def run_dynamic(bundle: Any, coverage_path: str | None = None, trace_path: str | None = None) -> dict[str, Any]: ...
