from collections.abc import Callable as Callable
from dataclasses import dataclass, field
from typing import Any

from _typeshed import Incomplete

from cogant.api import orchestration as orchestration
from cogant.api.bundle import Bundle as Bundle

logger: Incomplete

@dataclass
class PipelineConfig:
    stages: list[str] = field(default_factory=Incomplete)
    skip_stages: list[str] = field(default_factory=list)
    plugins: dict[str, dict[str, Any]] = field(default_factory=dict)
    output_dir: str = ...
    verbose: bool = ...
    dry_run: bool = ...
    layout_output: bool = ...
    skip_dynamic: bool = ...
    coverage_path: str | None = ...
    trace_path: str | None = ...
    incremental_since: str | None = ...
    cache_dir: str | None = ...

class PipelineRunner:
    stage_handlers: dict[str, Callable[..., Any]]
    def __init__(self) -> None: ...
    def run(self, target: str, config: PipelineConfig | None = None) -> Bundle: ...
