from collections.abc import Callable as Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Self

from _typeshed import Incomplete

from cogant.api.bundle import Bundle as Bundle

@dataclass
class PipelineConfig:
    stages: list[str] = field(default_factory=Incomplete)
    skip_stages: list[str] = field(default_factory=list)
    plugins: dict[str, dict[str, Any]] = field(default_factory=dict)
    output_dir: str = ...
    verbose: bool = ...
    dry_run: bool = ...
    layout_output: bool = ...
    render_visualizations: bool = ...
    skip_dynamic: bool = ...
    coverage_path: str | None = ...
    trace_path: str | None = ...
    incremental_since: str | None = ...
    cache_dir: str | None = ...
    min_confidence: float = ...
    profiling_enabled: bool = ...
    upstream_gnn_validation: bool = ...
    upstream_gnn_pipeline: bool = ...
    upstream_gnn_only_steps: list[int] | None = ...
    upstream_gnn_skip_steps: list[int] = field(default_factory=list)
    upstream_gnn_output_dir: str | None = ...
    upstream_gnn_frameworks: str = ...
    upstream_gnn_llm_model: str | None = ...
    def validate(self) -> list[str]: ...
    def with_profiling(self) -> Self: ...
    def to_yaml(self, path: str | Path) -> None: ...
    @classmethod
    def from_yaml(cls, path: str | Path) -> Self: ...

class PipelineRunner:
    stage_handlers: dict[str, Callable[..., Any]]
    def __init__(self) -> None: ...
    def run(self, target: str, config: PipelineConfig | None = None) -> Bundle: ...

@dataclass
class PipelineResult:
    bundle: Bundle
    timing: dict[str, float] = field(default_factory=dict)
    stage_outputs: dict[str, Any] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)
    total_duration_ms: float = ...
