from dataclasses import dataclass
from typing import Any

from _typeshed import Incomplete as Incomplete

logger: Incomplete

@dataclass
class ReviewableMapping:
    id: str
    source: str
    target: str
    confidence: float
    evidence: str
    status: str = ...
    notes: str = ...

class ReviewAPI:
    current_bundle: Any | None
    mappings: list[ReviewableMapping]
    review_state: dict[str, Any]
    def __init__(self) -> None: ...
    def load_bundle(self, bundle_path: str) -> None: ...
    def present_mapping(self, mapping_id: str) -> ReviewableMapping: ...
    def accept_mapping(self, mapping_id: str, notes: str = '') -> None: ...
    def reject_mapping(self, mapping_id: str, reason: str = '') -> None: ...
    def edit_mapping(self, mapping_id: str, **changes: Any) -> ReviewableMapping: ...
    def get_review_summary(self) -> dict[str, int]: ...
    def save_curated_bundle(self, output_path: str) -> None: ...
    def get_pending_mappings(self) -> list[ReviewableMapping]: ...
    def get_accepted_mappings(self) -> list[ReviewableMapping]: ...
    def get_rejected_mappings(self) -> list[ReviewableMapping]: ...
