from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from pathlib import Path
from typing import Any

class SessionStatus(StrEnum):
    CREATED = "created"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    EXPIRED = "expired"

@dataclass
class Session:
    target: str = ...
    workspace: str | None = ...
    repo_path: Path | None = ...
    created_at: datetime = field(default_factory=datetime.now)
    syntax_tree: dict[str, Any] | None = ...
    trace_bundle: dict[str, Any] | None = ...
    program_graph: dict[str, Any] | None = ...
    gnn_model: dict[str, Any] | None = ...
    state_space: dict[str, Any] | None = ...
    process_model: dict[str, Any] | None = ...
    export_artifacts: dict[str, Path] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)
    def __post_init__(self) -> None: ...
    def _bundle_internal(self) -> Any: ...
    @classmethod
    def from_target(cls, path_or_url: str) -> Session: ...
    def extract_static(self) -> dict[str, Any]: ...
    def extract_dynamic(
        self, coverage_path: str | None = None, trace_path: str | None = None
    ) -> dict[str, Any]: ...
    def build_graph(self) -> dict[str, Any]: ...
    def translate_to_gnn(self) -> dict[str, Any]: ...
    def compile_state_space(self) -> dict[str, Any]: ...
    def export_all(self, output_dir: str, layout: bool = False) -> Session: ...

@dataclass
class SessionManager:
    ttl_seconds: int = ...
    _sessions: dict[str, Session] = field(default_factory=dict)
    def create(self, target: str, workspace: str | None = None) -> tuple[str, Session]: ...
    def get(self, session_id: str) -> Session | None: ...
    def update_status(self, session_id: str, status: SessionStatus) -> bool: ...
    def cleanup_expired(self) -> int: ...
    def stats(self) -> dict[str, Any]: ...
