from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from _typeshed import Incomplete as Incomplete

logger: Incomplete

@dataclass
class Session:
    target: str = ...
    workspace: str | None = ...
    repo_path: Path | None = ...
    created_at: datetime = field(default_factory=datetime.now)
    syntax_tree: dict[str, Any] | None = ...
    trace_bundle: dict[str, Any] | None = ...
    program_graph: dict[str, Any] | None = ...
    gnn_model: dict[str, Any] | None = ...
    state_space: dict[str, Any] | None = ...
    process_model: dict[str, Any] | None = ...
    export_artifacts: dict[str, Path] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)
    def __post_init__(self) -> None: ...
    @classmethod
    def from_target(cls, path_or_url: str) -> Session: ...
    def extract_static(self) -> dict[str, Any]: ...
    def extract_dynamic(self, coverage_path: str | None = None, trace_path: str | None = None) -> dict[str, Any]: ...
    def build_graph(self) -> dict[str, Any]: ...
    def translate_to_gnn(self) -> dict[str, Any]: ...
    def compile_state_space(self) -> dict[str, Any]: ...
    def export_all(self, output_dir: str, layout: bool = False) -> Session: ...
