from typing import Any

def load() -> dict[str, Any]: ...
def version() -> str: ...
def test_count() -> int: ...
def coverage() -> float: ...
def mypy_errors() -> int: ...
def isomorphic_count() -> int: ...
def total_targets() -> int: ...
def mean_epsilon() -> float: ...
def epsilon_for(name: str) -> float | None: ...
def bibliography_entries() -> int: ...
