from typing import Any

def load() -> dict[str, Any]: ...
def version() -> str: ...
def test_count() -> int: ...
def coverage() -> float: ...
def mypy_errors() -> int: ...
def role_preserved_count() -> int: ...
def strict_isomorphism_count() -> int: ...
def isomorphic_count() -> int: ...
def total_targets() -> int: ...
def mean_role_preservation_score() -> float: ...
def mean_epsilon() -> float: ...
def role_preservation_score_for(name: str) -> float | None: ...
def epsilon_for(name: str) -> float | None: ...
def bibliography_entries() -> int: ...
