from typing import Any, Protocol

__all__ = [
    "Translatable",
    "Analyzable",
    "Serializable",
    "Visualizable",
    "Validatable",
    "Exportable",
    "Exportable2",
    "PipelineStage",
    "TranslationRule",
    "GraphBackend",
    "StaticAnalyzer",
    "DiagramRenderer",
    "ReportGenerator",
    "NetworkAnalyzer",
]

class Translatable(Protocol): ...
class Analyzable(Protocol): ...
class Serializable(Protocol): ...
class Visualizable(Protocol): ...
class Validatable(Protocol): ...
class Exportable(Protocol): ...
class Exportable2(Protocol): ...

class PipelineStage(Protocol):
    name: str
    def run(self, context: Any) -> Any: ...

class TranslationRule(Protocol): ...
class GraphBackend(Protocol): ...
class StaticAnalyzer(Protocol): ...
class DiagramRenderer(Protocol): ...
class ReportGenerator(Protocol): ...
class NetworkAnalyzer(Protocol): ...
