from typing import Any

from _typeshed import Incomplete

from cogant.schemas.core import Edge, Node

__all__ = ['RUST_AVAILABLE', 'RustProgramGraphAdapter', 'build_program_graph', 'create_example_graph', 'get_program_graph_impl', 'rust_version']

RUST_AVAILABLE: bool

def get_program_graph_impl() -> type[Any]: ...
def rust_version() -> str | None: ...
def create_example_graph() -> Any: ...

class RustProgramGraphAdapter:
    repo_uri: Incomplete
    def __init__(self, repo_uri: str) -> None: ...
    def add_node(self, kind: Any, name: str, qualified_name: str, path: str | None = None, language: str | None = None, source_range: dict[str, Any] | None = None, metadata: dict[str, Any] | None = None) -> Node: ...
    def add_edge(self, source_id: str, target_id: str, kind: Any, weight: float = 1.0, metadata: dict[str, Any] | None = None, evidence_sources: list[str] | None = None) -> Edge | None: ...
    def finalize(self) -> Any: ...
    @property
    def graph(self) -> Any: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...

def build_program_graph(repo_uri: str = 'repo://unknown', use_rust: bool | None = None) -> Any: ...
