from dataclasses import dataclass
from typing import Any

@dataclass
class DriftScore:
    total_score: float
    architectural_score: float
    semantic_churn_score: float
    details: dict[str, Any]

class DriftAnalyzer:
    bundle_a: Any
    bundle_b: Any
    graph_a: Any
    graph_b: Any
    ss_a: Any
    ss_b: Any
    mappings_a: Any
    mappings_b: Any
    def __init__(self, bundle_a: dict[str, Any], bundle_b: dict[str, Any]) -> None: ...
    def analyze(self, bundle_a: dict[str, Any], bundle_b: dict[str, Any]) -> DriftScore: ...
    def compute_structural_drift(self) -> dict[str, Any]: ...
    def compute_semantic_drift(self) -> dict[str, Any]: ...
    def compute_state_space_drift(self) -> dict[str, Any]: ...
    def compute_architectural_drift_score(self) -> float: ...
    def compute_semantic_churn_score(self) -> float: ...
    def generate_diff_report(self) -> str: ...
    def generate_diff_mermaid(self) -> str: ...
    def report(self, score: DriftScore) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
