from _typeshed import Incomplete
from cogant.normalize.identities import IdentityResolver as IdentityResolver
from cogant.schemas.core import Edge as Edge, EdgeKind as EdgeKind, Node as Node, NodeKind as NodeKind
from cogant.schemas.graph import GraphMetadata as GraphMetadata, ProgramGraph as ProgramGraph
from typing import Any

class ProgramGraphBuilder:
    repo_uri: Incomplete
    identity_resolver: Incomplete
    graph: Incomplete
    def __init__(self, repo_uri: str) -> None: ...
    def add_node(self, kind: NodeKind, name: str, qualified_name: str, path: str | None = None, language: str | None = None, source_range: dict[str, Any] | None = None, metadata: dict[str, Any] | None = None) -> Node: ...
    def add_edge(self, source_id: str, target_id: str, kind: EdgeKind, weight: float = 1.0, metadata: dict[str, Any] | None = None, evidence_sources: list[str] | None = None) -> Edge | None: ...
    def get_node(self, node_id: str) -> Node | None: ...
    def get_neighbors(self, node_id: str) -> list[Node]: ...
    def find_path(self, source_id: str, target_id: str, max_depth: int = 10) -> list[str] | None: ...
    def get_subgraph(self, node_ids: list[str], include_neighbors: bool = False) -> ProgramGraph: ...
    def get_connected_components(self) -> list[list[str]]: ...
    def find_cycles(self) -> list[list[str]]: ...
    def get_statistics(self) -> dict[str, Any]: ...
    def finalize(self) -> ProgramGraph: ...
