from typing import Any

from _typeshed import Incomplete as Incomplete

from cogant.schemas.core import Edge as Edge
from cogant.schemas.core import EdgeKind as EdgeKind
from cogant.schemas.core import Node as Node
from cogant.schemas.core import NodeKind as NodeKind
from cogant.schemas.graph import ProgramGraph as ProgramGraph

class GraphQuery:
    graph: Incomplete
    def __init__(self, graph: ProgramGraph) -> None: ...
    def find_nodes_by_kind(self, kind: NodeKind) -> list[Node]: ...
    def filter_nodes(self, kind: NodeKind | None = None, language: str | None = None, name_pattern: str | None = None, metadata_filter: dict[str, Any] | None = None) -> list[Node]: ...
    def filter_edges(self, kind: EdgeKind | None = None, source_id: str | None = None, target_id: str | None = None, min_weight: float = 0.0) -> list[Edge]: ...
    def find_shortest_path(self, source_id: str, target_id: str) -> list[str] | None: ...
    def find_all_paths(self, source_id: str, target_id: str, max_depth: int = 5) -> list[list[str]]: ...
    def compute_in_degree(self, node_id: str) -> int: ...
    def compute_out_degree(self, node_id: str) -> int: ...
    def compute_betweenness_centrality(self) -> dict[str, float]: ...
    def compute_closeness_centrality(self) -> dict[str, float]: ...
    def compute_degree_centrality(self) -> dict[str, float]: ...
    def find_connected_components(self) -> list[set[str]]: ...
    def find_cycles(self, max_cycle_size: int = 10) -> list[list[str]]: ...
    def extract_subgraph_by_kind(self, node_kinds: list[NodeKind]) -> ProgramGraph: ...
    def get_dependency_chain(self, node_id: str, max_depth: int = 5) -> dict[str, list[str]]: ...
    def get_statistics(self) -> dict[str, Any]: ...
