from __future__ import annotations

from typing import Any
from xml.etree import ElementTree as ET

from cogant.schemas.graph import ProgramGraph as ProgramGraph

class GraphMLExporter:
    graph: ProgramGraph
    def __init__(self, program_graph: ProgramGraph) -> None: ...
    def export(self) -> str: ...
    def export_with_metadata(
        self, graph: ProgramGraph, mappings: dict[str, Any], output_path: str
    ) -> str: ...
    def _add_key_definitions(self, graphml: ET.Element, with_semantic: bool = ...) -> None: ...
    def _add_node(self, graph_elem: ET.Element, node: Any) -> None: ...
    def _add_node_with_metadata(
        self, graph_elem: ET.Element, node: Any, mappings: dict[str, Any]
    ) -> None: ...
    def _add_edge(self, graph_elem: ET.Element, edge: Any) -> None: ...
    def _add_data(self, parent: ET.Element, key: str, value: str) -> None: ...
    def _prettify(self, xml_string: str) -> str: ...
