from __future__ import annotations

from typing import Any

class JSONSchemaExporter:
    def __init__(self) -> None: ...
    def export_gnn_bundle_schema(self) -> dict[str, Any]: ...
    def export_program_graph_schema(self) -> dict[str, Any]: ...
    def export_semantic_mappings_schema(self) -> dict[str, Any]: ...
    def export_pipeline_result_schema(self) -> dict[str, Any]: ...
