from __future__ import annotations

from cogant.markov.partition import MarkovBlanket as MarkovBlanket
from cogant.schemas.graph import ProgramGraph as ProgramGraph

class SVGExporter:
    _graphviz_available: bool
    def __init__(self) -> None: ...
    def export_program_graph(self, graph: ProgramGraph, output_path: str) -> str: ...
    def export_markov_blanket(self, blanket: MarkovBlanket, output_path: str) -> str: ...
    def graph_to_dot(self, graph: ProgramGraph) -> str: ...
    def blanket_to_dot(self, blanket: MarkovBlanket) -> str: ...
    def _safe_id(self, node_id: str) -> str: ...
    def _get_node_color(self, kind: str) -> str: ...
    def _check_graphviz(self) -> bool: ...
    def _render_dot_to_svg(self, dot_string: str, output_path: str) -> str: ...
