from __future__ import annotations

from typing import Any

from cogant.schemas.graph import ProgramGraph as ProgramGraph

class TypedExporter:
    def __init__(self) -> None: ...
    def export_typed_graph(self, graph: ProgramGraph) -> dict[str, Any]: ...
    def export_graphviz_dot(self, graph: ProgramGraph) -> str: ...
    def export_cytoscape_json(self, graph: ProgramGraph) -> dict[str, Any]: ...
    def export_adjacency_matrix(self, graph: ProgramGraph) -> dict[str, Any]: ...
    def to_jsonlines(self, items: list[Any], output_path: str) -> str: ...
    def to_arrow_ipc(self, items: list[Any], output_path: str) -> str: ...
    def export_summary(self, pipeline_result: dict[str, Any]) -> dict[str, Any]: ...
