from typing import Any

from _typeshed import Incomplete

from cogant.schemas.core import NodeKind as NodeKind
from cogant.schemas.graph import ProgramGraph as ProgramGraph

logger: Incomplete

class TypedExporter:
    def __init__(self) -> None: ...
    def export_typed_graph(self, graph: ProgramGraph) -> dict[str, Any]: ...
    def export_graphviz_dot(self, graph: ProgramGraph) -> str: ...
    def export_cytoscape_json(self, graph: ProgramGraph) -> dict[str, Any]: ...
    def export_adjacency_matrix(self, graph: ProgramGraph) -> dict[str, Any]: ...
