from dataclasses import dataclass
from pathlib import Path
from typing import Any

from _typeshed import Incomplete

logger: Incomplete

@dataclass
class ChangedFile:
    path: Path
    change_type: str

class IncrementalIngester:
    repo_path: Incomplete
    git_timeout: Incomplete
    def __init__(self, repo_path: Path, git_timeout: float = 30.0) -> None: ...
    def is_git_repo(self) -> bool: ...
    def changed_since(self, ref: str = 'HEAD~1') -> list[ChangedFile]: ...
    def changed_since_commit(self, commit_hash: str) -> list[ChangedFile]: ...
    def working_tree_changes(self) -> list[ChangedFile]: ...
    def python_files_changed_since(self, ref: str = 'HEAD~1') -> list[Path]: ...
    def source_files_changed_since(self, ref: str = 'HEAD~1', extensions: set[str] | None = None) -> list[Path]: ...

def get_changed_files(repo_path: Path, since_commit: str, extensions: set[str] | None = None) -> list[Path]: ...
def apply_incremental_patch(cached_stage_results: dict[str, Any], new_stage_results: dict[str, Any], changed_files: list[Path]) -> dict[str, Any]: ...
