from dataclasses import dataclass
from pathlib import Path
from typing import Any

from _typeshed import Incomplete

class _TomlLib:
    @staticmethod
    def load(f: Any) -> dict[str, Any]: ...

logger: Incomplete

@dataclass
class Dependency:
    name: str
    version: str | None = ...
    is_dev: bool = ...
    is_local: bool = ...

class ManifestParser:
    def parse(self, path: Path) -> tuple[dict[str, Any], list[Dependency]]: ...
    def parse_setup_py(self, path: Path) -> tuple[dict[str, Any], list[Dependency]]: ...
    def parse_pyproject_toml(self, path: Path) -> tuple[dict[str, Any], list[Dependency]]: ...
    def parse_requirements_txt(self, path: Path) -> list[Dependency]: ...
    def parse_package_json(self, path: Path) -> tuple[dict[str, Any], list[Dependency]]: ...
    def parse_cargo_toml(self, path: Path) -> tuple[dict[str, Any], list[Dependency]]: ...
