from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from cogant.schemas.graph import ProgramGraph as ProgramGraph
from cogant.schemas.semantic import SemanticMapping as SemanticMapping

class StateVariableType(StrEnum):
    BOOLEAN = "boolean"
    DISCRETE = "discrete"
    CONTINUOUS = "continuous"
    CATEGORICAL = "categorical"
    VECTOR = "vector"
    COMPOSITE = "composite"

class ConfidenceLevel(StrEnum):
    DEFINITE = "definite"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    UNCERTAIN = "uncertain"

@dataclass
class StateVariable:
    id: str
    name: str
    var_type: StateVariableType
    node_id: str
    cardinality: int | None = ...
    domain: list[Any] | None = ...
    factors: list[str] | None = ...
    is_discrete: bool = ...
    confidence: ConfidenceLevel = ...
    description: str | None = ...
    mutations: list[str] = field(default_factory=list)
    reads: list[str] = field(default_factory=list)
    observable: bool = ...
    def __repr__(self) -> str: ...
    def merge(self, other: StateVariable) -> StateVariable: ...

@dataclass
class FactorizationInfo:
    factors: list[str]
    independence_score: float
    dependencies: dict[str, list[str]]

@dataclass
class ObservationVar:
    id: str
    name: str
    source_node_id: str
    modality_type: str
    cardinality: int | None = ...
    confidence: ConfidenceLevel = ...
    description: str | None = ...
    def __repr__(self) -> str: ...
    def is_compatible_with(self, hidden: StateVariable) -> bool: ...

class StateVariableExtractor:
    graph: Any
    state_variables: dict[str, StateVariable]
    factorization_map: dict[str, FactorizationInfo]
    def __init__(self, program_graph: ProgramGraph) -> None: ...
    def extract(
        self, semantic_mappings: dict[str, SemanticMapping]
    ) -> dict[str, StateVariable]: ...
    def get_state_variables(self) -> dict[str, StateVariable]: ...
    def get_factorization(self, var_id: str) -> FactorizationInfo | None: ...
    def compute_dimensionality(self) -> int: ...

class VariableRegistry:
    hidden_vars: dict[str, StateVariable]
    observation_vars: dict[str, ObservationVar]
    def __init__(self) -> None: ...
    def add_hidden(self, var: StateVariable) -> None: ...
    def add_observation(self, obs: ObservationVar) -> None: ...
    def get_hidden(self, var_id: str) -> StateVariable | None: ...
    def get_observation(self, obs_id: str) -> ObservationVar | None: ...
    def find_by_role(self, role: str) -> list[StateVariable | ObservationVar]: ...
    def to_list(self) -> list[dict[str, Any]]: ...
