"""COGANT correctness law 1: forward idempotency.

Processing the same input graph through the forward translation
pipeline twice must yield the same set of semantic mappings. This is
the "stateless fingerprint" property of forward: no hidden global
state, no clock-dependent derivation, no ordering bugs in the
fixpoint.

We prove this on synthetic in-memory ``ProgramGraph`` instances
generated by a Hypothesis composite strategy. The real forward
pipeline (``Session.extract_static`` → ``build_graph`` →
``translate_to_gnn``) is far too slow to run 30 times in a property
test, but the ``TranslationEngine`` is the authoritative "forward"
stage for the idempotency question: it is the component whose output
defines ``R(G)`` in the role multiset sense used by
``cogant.reverse.idempotency``. Running it twice on the same graph
is a direct falsification test for the law.

A single failing case (two runs producing different mapping sets)
would disprove forward idempotency on that graph.
"""

from __future__ import annotations

import pytest
from hypothesis import HealthCheck, given, settings, strategies as st

from cogant.graph.builder import ProgramGraphBuilder
from cogant.schemas.core import EdgeKind, NodeKind
from cogant.schemas.graph import ProgramGraph
from cogant.translate.engine import TranslationEngine
from cogant.translate.rules import (
    ActionRule,
    ContainmentRule,
    InheritanceRule,
    MutatingSubsystemRule,
    ObservationRule,
    PolicyRule,
    ReadOnlyInputRule,
)

pytestmark = pytest.mark.property


# ---------------------------------------------------------------------------
# Fixture strategy: small synthetic program graphs.
# ---------------------------------------------------------------------------


_NODE_KINDS = (
    NodeKind.MODULE,
    NodeKind.CLASS,
    NodeKind.METHOD,
    NodeKind.FUNCTION,
    NodeKind.VARIABLE,
)

_EDGE_KINDS = (
    EdgeKind.CONTAINS,
    EdgeKind.READS,
    EdgeKind.WRITES,
    EdgeKind.MUTATES,
    EdgeKind.CALLS,
    EdgeKind.DEPENDS_ON,
    EdgeKind.INHERITS,
)

_NAMES = (
    "get_value",
    "set_value",
    "handle_event",
    "process_item",
    "dispatch",
    "Service",
    "Store",
    "controller",
    "state",
    "config",
)


@st.composite
def synthetic_graph(draw, min_nodes: int = 3, max_nodes: int = 12) -> ProgramGraph:
    """Build a small, well-formed ProgramGraph with unique qualified names."""
    n = draw(st.integers(min_value=min_nodes, max_value=max_nodes))
    builder = ProgramGraphBuilder(repo_uri="hypothesis://law1")

    root = builder.add_node(
        kind=NodeKind.MODULE,
        name="root_module",
        qualified_name="law1_root",
        path="root.py",
        language="python",
    )
    nodes = [root]
    for i in range(n - 1):
        kind = draw(st.sampled_from(_NODE_KINDS))
        base = draw(st.sampled_from(_NAMES))
        node = builder.add_node(
            kind=kind,
            name=base,
            qualified_name=f"{base}_{i}",
            path=f"law1_{i}.py",
            language="python",
        )
        nodes.append(node)

    n_edges = draw(st.integers(min_value=0, max_value=2 * n))
    for _ in range(n_edges):
        src = draw(st.sampled_from(nodes))
        tgt = draw(st.sampled_from(nodes))
        if src.id == tgt.id:
            continue
        builder.add_edge(src.id, tgt.id, draw(st.sampled_from(_EDGE_KINDS)))

    return builder.finalize()


def _fresh_engine() -> TranslationEngine:
    """Construct a fresh engine with the shipping rule set."""
    engine = TranslationEngine()
    engine.register_rule(ReadOnlyInputRule())
    engine.register_rule(MutatingSubsystemRule())
    engine.register_rule(ObservationRule())
    engine.register_rule(ActionRule())
    engine.register_rule(PolicyRule())
    engine.register_rule(InheritanceRule())
    engine.register_rule(ContainmentRule())
    return engine


def _mapping_signature(mappings) -> set[tuple]:
    """Stable per-mapping fingerprint immune to id/timestamp drift.

    Each semantic mapping carries a UUID ``id`` and a creation
    timestamp that legitimately differ between runs. The *content*
    of a forward run — the set of (kind, sorted_fragment_node_ids)
    tuples — is what we expect to be bit-identical across invocations.
    """
    sig: set[tuple] = set()
    for m in mappings:
        frag = tuple(sorted(m.graph_fragment_node_ids))
        sig.add((m.kind.value, frag))
    return sig


# ---------------------------------------------------------------------------
# Law 1: forward(G) == forward(G) — two runs produce the same mappings.
# ---------------------------------------------------------------------------


@given(graph=synthetic_graph())
@settings(
    max_examples=30,
    deadline=500,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much],
)
def test_forward_is_idempotent_on_synthetic_graph(graph: ProgramGraph) -> None:
    """Two forward runs on the same graph must agree on the mapping set."""
    first = _fresh_engine().translate(graph)
    second = _fresh_engine().translate(graph)

    sig1 = _mapping_signature(first)
    sig2 = _mapping_signature(second)

    assert sig1 == sig2, (
        f"forward is not idempotent: first={sig1 - sig2} "
        f"second={sig2 - sig1} on graph with {len(graph.nodes)} nodes / "
        f"{len(graph.edges)} edges"
    )


@given(graph=synthetic_graph(min_nodes=5, max_nodes=15))
@settings(
    max_examples=30,
    deadline=500,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much],
)
def test_forward_idempotent_on_three_runs(graph: ProgramGraph) -> None:
    """A third forward run must also agree — no cumulative drift."""
    sigs = [_mapping_signature(_fresh_engine().translate(graph)) for _ in range(3)]
    assert sigs[0] == sigs[1] == sigs[2], (
        f"forward run drift across 3 invocations: {sigs}"
    )


@given(graph=synthetic_graph(min_nodes=3, max_nodes=8))
@settings(
    max_examples=30,
    deadline=500,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much],
)
def test_forward_idempotent_mapping_count_stable(graph: ProgramGraph) -> None:
    """The *cardinality* of the mapping set must be stable across runs.

    Even without a full content fingerprint, a non-idempotent forward
    stage would manifest as a fluctuating mapping count. This is a
    weaker but independent check that strengthens the falsifier.
    """
    counts = [len(_fresh_engine().translate(graph)) for _ in range(3)]
    assert counts[0] == counts[1] == counts[2], (
        f"forward mapping cardinality unstable across runs: {counts}"
    )
