"""Tests for current GNN 2.0.0 schema detection."""

from cogant.schema import (
    CURRENT_GNN_VERSION,
    GNN_V2_REQUIRED_SECTIONS,
    detect_version,
)
from cogant.schema.versions import (
    UNSUPPORTED_GNN_VERSION,
)

CURRENT_GNN_TEXT = """\
## GNNSection
ExampleModel

## GNNVersionAndFlags
GNN v2.0.0

## ModelName
ExampleModel

## StateSpaceBlock
s_f0[2,1,type=int]

## Connections
D_f0>s_f0

## InitialParameterization
D_f0={ (0.5, 0.5) }

## Equations
Q(s) = softmax(ln(D))

## Time
Static

## ActInfOntologyAnnotation
s_f0=HiddenState

## ModelParameters
num_hidden_states=1

## Footer
Generated by COGANT.

## Signature
pending
"""


def test_detect_version_current() -> None:
    assert detect_version(CURRENT_GNN_TEXT) == CURRENT_GNN_VERSION


def test_detect_version_unsupported_without_current_marker() -> None:
    assert detect_version("## GNNVersionAndFlags\nGNN experimental\n") == UNSUPPORTED_GNN_VERSION


def test_detect_version_never_raises() -> None:
    assert detect_version(None) == UNSUPPORTED_GNN_VERSION  # type: ignore[arg-type]


def test_required_sections_are_current_contract() -> None:
    assert "GNNVersionAndFlags" in GNN_V2_REQUIRED_SECTIONS
    assert "Signature" in GNN_V2_REQUIRED_SECTIONS
    assert len(GNN_V2_REQUIRED_SECTIONS) >= 12
