from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from cogant.schemas.core import Edge as Edge
from cogant.schemas.core import EdgeKind as EdgeKind
from cogant.schemas.core import Node as Node
from cogant.schemas.core import NodeKind as NodeKind

@dataclass
class GraphMetadata:
    repo_uri: str
    languages: set[str] = field(default_factory=set)
    version: str = ...
    created_at: datetime = field(default_factory=Incomplete)
    updated_at: datetime = field(default_factory=Incomplete)
    evidence_sources: list[str] = field(default_factory=list)
    custom_metadata: dict[str, Any] = field(default_factory=dict)

@dataclass
class ProgramGraph:
    metadata: GraphMetadata
    nodes: dict[str, Node] = field(default_factory=dict)
    edges: dict[str, Edge] = field(default_factory=dict)
    def add_node(self, node: Node) -> None: ...
    def remove_node(self, node_id: str) -> None: ...
    def add_edge(self, edge: Edge) -> None: ...
    def remove_edge(self, edge_id: str) -> None: ...
    def get_node(self, node_id: str) -> Node | None: ...
    def get_edges_from(self, node_id: str) -> list[Edge]: ...
    def get_edges_to(self, node_id: str) -> list[Edge]: ...
    def get_neighbors(self, node_id: str) -> list[Node]: ...
    def get_nodes_by_kind(self, kind: NodeKind) -> list[Node]: ...
    def get_edges_by_kind(self, kind: EdgeKind) -> list[Edge]: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
