#!/usr/bin/env python3
"""Regenerate the ``ablation`` block in ``cogant/evaluation/METRICS.yaml``.

Run from any directory; all paths are anchored on ``__file__``. The historical
convention was to run from the ``cogant/`` package root, and that still works::

    cd cogant && uv run python ../tools/regenerate_ablation.py

or equivalently::

    uv run python tools/regenerate_ablation.py
    uv run python projects/cogant/tools/regenerate_ablation.py  # parent template root

The script runs the live ingest/static/normalize/graph/translate/state-space/
matrix pipeline on the seven packaged fixtures, computes the rule-family,
fixpoint, and matrix-fallback ablation summaries, then merges the resulting
``ablation:`` block into ``cogant/evaluation/METRICS.yaml`` while preserving
the canonical auto-generated header and all existing top-level keys.

Exit codes
----------
* ``0`` — ablation block written successfully.
* ``1`` — fatal error (missing ``cogant/`` tree, fixture build failure,
          write failure, etc.).
"""

from __future__ import annotations

import math
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).parent.parent
COGANT_DIR = REPO_ROOT / "cogant"
EVAL_DIR = COGANT_DIR / "evaluation"

sys.path.insert(0, str((COGANT_DIR / "py").resolve()))

# These imports are intentionally below the sys.path bootstrap above: the
# cogant package lives under cogant/py/ and is only importable once that
# directory is on sys.path. This mirrors the runtime-path pattern used by
# tools/regenerate_metrics.py. E402 is suppressed for exactly these lines.
from cogant.api.bundle import Bundle  # noqa: E402
from cogant.api.orchestration import (  # noqa: E402
    _default_translation_engine,
    run_graph,
    run_ingest,
    run_normalize,
    run_static,
)
from cogant.gnn.matrices import GNNMatrices  # noqa: E402
from cogant.statespace.compiler import StateSpaceCompiler  # noqa: E402

PACKAGED_FIXTURES: list[tuple[str, str]] = [
    ("zoo", "01_simple_state"),
    ("control_positive", "calculator"),
    ("control_positive", "event_pipeline"),
    ("control_positive", "flask_mini"),
    ("real_world", "flask_app"),
    ("real_world", "requests_lib"),
    ("real_world", "json_stdlib"),
]

RULE_FAMILIES: dict[str, set[str]] = {
    "structural": {
        "read_only_input",
        "mutating_subsystem",
        "inheritance",
        "containment",
        "data_pipeline",
    },
    "behavioral": {"orchestrator", "test_assertion", "event_bus", "state_machine"},
    "control": {"config", "feature_flag", "parameter"},
    "semantic": {"observation", "action", "policy", "preference", "context"},
    "resilience": {
        "retry_pattern",
        "error_boundary",
        "singleton_access",
        "circuit_breaker",
        "rate_limiter",
    },
}

METRICS_HEADER = (
    "# cogant/evaluation/METRICS.yaml\n"
    "# AUTO-GENERATED by tools/regenerate_metrics.py\n"
    "# DO NOT EDIT BY HAND. Run: cd cogant && uv run python ../tools/regenerate_metrics.py\n\n"
)


def _fixture_path(bucket: str, name: str) -> Path:
    return (COGANT_DIR / "examples" / bucket / name).resolve()


def _mapping_kind_counts(mappings: list[Any]) -> dict[str, int]:
    counts: Counter[str] = Counter()
    for mapping in mappings:
        kind = getattr(mapping, "kind", "")
        kind_name = getattr(kind, "name", None)
        if kind_name is None:
            kind_name = str(getattr(kind, "value", kind)).upper()
        counts[str(kind_name)] += 1
    return dict(sorted(counts.items()))


def _is_uniform_row(row: list[float]) -> bool:
    if not row:
        return False
    expected = 1.0 / len(row)
    return all(math.isclose(value, expected, abs_tol=1e-9) for value in row)


def _count_identity_b_actions(tensor: list[list[list[float]]]) -> tuple[int, int]:
    if not tensor or not tensor[0] or not tensor[0][0]:
        return 0, 0
    n_states = len(tensor)
    n_actions = len(tensor[0][0])
    identity_actions = 0
    for action_idx in range(n_actions):
        is_identity = True
        for next_state_idx in range(n_states):
            for current_state_idx in range(n_states):
                expected = 1.0 if next_state_idx == current_state_idx else 0.0
                if not math.isclose(
                    tensor[next_state_idx][current_state_idx][action_idx],
                    expected,
                    abs_tol=1e-9,
                ):
                    is_identity = False
                    break
            if not is_identity:
                break
        if is_identity:
            identity_actions += 1
    return identity_actions, n_actions


def _is_uniform_vector(vector: list[float]) -> bool:
    if not vector:
        return False
    expected = 1.0 / len(vector)
    return all(math.isclose(value, expected, abs_tol=1e-9) for value in vector)


def compute_ablation(fixtures: list[tuple[str, str]]) -> dict[str, Any]:
    """Run the live ablation pipeline for the supplied packaged fixtures."""
    rule_family: dict[str, dict[str, int]] = {}
    by_mapping_kind: dict[str, dict[str, dict[str, int]]] = {}
    fixpoint: dict[str, dict[str, int]] = {}
    matrix_fallback: dict[str, dict[str, int | bool]] = {}
    total = len(fixtures)

    for index, (bucket, name) in enumerate(fixtures, start=1):
        fixture_id = f"{bucket}/{name}"
        print(f"  [{index}/{total}] {fixture_id}", file=sys.stderr)
        try:
            fixture_path = _fixture_path(bucket, name)
            if not fixture_path.is_dir():
                raise FileNotFoundError(f"fixture path not found: {fixture_path}")

            bundle = Bundle(target=str(fixture_path))
            run_ingest(str(fixture_path), bundle)
            run_static(bundle)
            run_normalize(bundle)
            run_graph(bundle, str(fixture_path))

            program_graph = bundle.artifacts["_program_graph"]
            baseline_engine = _default_translation_engine()
            baseline = baseline_engine.translate(program_graph)
            baseline_total = len(baseline)
            baseline_kind_counts = _mapping_kind_counts(baseline)

            family_row: dict[str, Any] = {
                "baseline_mappings_total": baseline_total,
                "baseline_by_mapping_kind": baseline_kind_counts,
            }
            family_kind_row: dict[str, dict[str, int]] = {}
            for family_name, removed_rules in RULE_FAMILIES.items():
                kept = [rule.name for rule in baseline_engine.rules if rule.name not in removed_rules]
                ablated = baseline_engine.translate(program_graph, rule_filter=kept)
                family_row[f"{family_name}_delta"] = baseline_total - len(ablated)
                ablated_kind_counts = _mapping_kind_counts(ablated)
                all_kinds = sorted(set(baseline_kind_counts) | set(ablated_kind_counts))
                family_kind_row[family_name] = {
                    kind: baseline_kind_counts.get(kind, 0) - ablated_kind_counts.get(kind, 0)
                    for kind in all_kinds
                }
            rule_family[name] = family_row
            by_mapping_kind[name] = family_kind_row

            fixpoint_row: dict[str, int] = {}
            for iteration_cap in (1, 2, 5, 10):
                engine = _default_translation_engine()
                engine.max_iterations = iteration_cap
                fixpoint_row[f"k{iteration_cap}"] = len(engine.translate(program_graph))
            fixpoint[name] = fixpoint_row

            baseline_by_id = {mapping.id: mapping for mapping in baseline}
            state_space = StateSpaceCompiler(program_graph, schema_name=name).compile(baseline_by_id)
            matrices = GNNMatrices(program_graph, baseline_by_id, state_space)
            matrix_a = matrices.compute_A()
            matrix_b = matrices.compute_B()
            matrix_c = matrices.compute_C()
            matrix_d = matrices.compute_D()

            b_identity, b_total = _count_identity_b_actions(matrix_b)
            # A is column-stochastic (P(o|s)): a "fallback" column is a hidden
            # state whose likelihood over observations is the maximum-entropy
            # uniform default — i.e. no observation reads/observes that state,
            # so it carries no discriminating evidence. Count uniform COLUMNS
            # (the correct axis for P(o|s)); the legacy row count is invalid
            # under the column-stochastic convention.
            n_obs_a = len(matrix_a)
            n_states_a = len(matrix_a[0]) if matrix_a and matrix_a[0] else 0
            a_cols_uniform = sum(
                1
                for j in range(n_states_a)
                if _is_uniform_vector([matrix_a[i][j] for i in range(n_obs_a)])
            )
            matrix_fallback[name] = {
                "a_cols_uniform": a_cols_uniform,
                "a_cols_total": n_states_a,
                "b_actions_identity": b_identity,
                "b_actions_total": b_total,
                "c_entries_zero": sum(
                    1 for value in matrix_c if math.isclose(value, 0.0, abs_tol=1e-9)
                ),
                "c_entries_total": len(matrix_c),
                "d_uniform": _is_uniform_vector(matrix_d),
            }
        except Exception as exc:
            raise RuntimeError(f"fixture build failed for {fixture_id}") from exc

    return {
        "rule_family": rule_family,
        "by_mapping_kind": by_mapping_kind,
        "fixpoint": fixpoint,
        "matrix_fallback": matrix_fallback,
    }


def main() -> None:
    print("Regenerating ablation metrics...", file=sys.stderr)

    if not COGANT_DIR.is_dir():
        print(
            f"ERROR: cogant directory not found at {COGANT_DIR}. "
            "Are you running from a stripped checkout?",
            file=sys.stderr,
        )
        sys.exit(1)

    metrics_path = EVAL_DIR / "METRICS.yaml"
    if not metrics_path.is_file():
        print(f"ERROR: existing metrics file not found at {metrics_path}", file=sys.stderr)
        sys.exit(1)

    try:
        ablation = compute_ablation(PACKAGED_FIXTURES)
        text = metrics_path.read_text(encoding="utf-8")
        if not text.startswith(METRICS_HEADER):
            raise ValueError("METRICS.yaml header does not match the canonical 3-line header")
        data = yaml.safe_load(text[len(METRICS_HEADER) :]) or {}
        if not isinstance(data, dict):
            raise TypeError("METRICS.yaml body is not a mapping")
        data["ablation"] = ablation
        yaml_str = yaml.dump(
            data,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )
        metrics_path.write_text(METRICS_HEADER + yaml_str, encoding="utf-8")
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"Written: {metrics_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
