"""Hypothesis-based fuzz harness for COGANT structural invariants.

This package holds property-style fuzz tests that exercise the ingest /
static / graph / translate / markov / matrix stages on tiny synthetic
program graphs generated by :mod:`hypothesis`. The goal is to shake out
regressions in the structural invariants the rest of COGANT relies on
(role coverage, mapping grounding, Markov blanket totality, matrix
stochasticity, rule determinism) without paying the cost of running the
full file-based ingest pipeline on every example.

All tests are marked ``fuzz`` so they can be selected or excluded from
regular CI runs with ``-m fuzz`` / ``-m "not fuzz"``.
"""
