from _typeshed import Incomplete
from cogant.schemas.graph import ProgramGraph
from cogant.statespace.compiler import StateSpaceModel
from typing import Any

__all__ = ['GNNMatrices']

class GNNMatrices:
    graph: Incomplete
    state_space: Incomplete
    def __init__(self, graph: ProgramGraph, mappings: Any, state_space: StateSpaceModel) -> None: ...
    @property
    def n_states(self) -> int: ...
    @property
    def n_obs(self) -> int: ...
    @property
    def n_actions(self) -> int: ...
    def compute_A(self) -> list[list[float]]: ...
    def compute_B(self) -> list[list[list[float]]]: ...
    def compute_C(self) -> list[float]: ...
    def compute_D(self) -> list[float]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_gnn_markdown_block(self) -> str: ...
    def validate_shapes(self) -> tuple[bool, list[str]]: ...
